### ISSUE TITLE
React Unit webgl not working for Safari

### ISSUE THREAD

**Issue by walia4** [jeffreylanters/react-unity-webgl#101]
Hi,
I was integrating  my unity code with react using the react-unity-webgl module. And I came across this error message. It's working fine for mobile safari browser but not mac safari browser. It would be really great if you can help.

errror_message: **Argument 1 ('sync') to WebGL2RenderingContext.clientWaitSync must be an instance of WebGLSync**

Attaching a Screenshots for reference......

<img width="1105" alt="Screenshot 2020-04-30 at 5 38 54 AM" src="https://user-images.githubusercontent.com/58622207/80659043-6cee1280-8aa5-11ea-94e0-aff28a435575.png">

<img width="1680" alt="Screenshot 2020-04-30 at 5 39 32 AM" src="https://user-images.githubusercontent.com/58622207/80659102-973fd000-8aa5-11ea-9f90-42ee5f8b0cf9.png">

<img width="1680" alt="Screenshot 2020-04-30 at 5 39 04 AM" src="https://user-images.githubusercontent.com/58622207/80659106-99099380-8aa5-11ea-8431-b78143c93dc2.png">

**Comment by jeffreylanters** [comment]
I doubt if this has anything to do with this library. Does a build straight out of Unity work? Without React?

**Comment by walia4** [comment]
@jeffreylanters Yes it works without the react. I have deployed it to my server to see the  results and everything was working fine

**Comment by walia4** [comment]
Yeah I have tried enabling and disabling WebGL 2 support in safari. Yet still having the same error.
