### ISSUE TITLE
Problem quitting game or changing current page

### ISSUE THREAD

**Issue by BartoszF** [jeffreylanters/react-unity-webgl#102]
**Describe the bug**
I cannot properly quit game using Application.Quit() nor unityContent.remove().
Also when changing page using react-router I have lots of errors.
When trying to quit game I have error loop saying

```
Quitting...
trap!
```

When trying to change page via history from react-router there is an error loop saying

```
Uncaught abort(229) at Error
```

When trying to change page via navbar using react-router

```
Uncaught abort(217) at Error
```

**To Reproduce**

```
export const GamePage = observer((props) => {
  let [progress, setProgress] = useState(0.0);
  let [loaded, setLoaded] = useState(false);
  let { gameStore } = useStores();
  const history = useHistory();

  let unityContent = new UnityContent(
    "/game/Build.json",
    "/game/UnityLoader.js",
    {
      adjustOnWindowResize: true,
    }
  );

  unityContent.on("progress", (progress) => {
    setProgress(progress);
  });

  unityContent.on("loaded", () => {
    setLoaded(true);
  });

  unityContent.on("quitted", () => {
    console.log("QUITTING"); //This isn't even called after Application.Quit()
  });

 //This is called from unity, just for testing
 //I'm trying such case when not calling Application.Quit()
  unityContent.on("Finished", (numFrames) => {
    console.log("Finished");
    gameStore.endSimulation(numFrames);
    unityContent.Remove();
    history.push(`/`);
  });

  return (
    <GameWrapper id="gameParent">
      {loaded == false && (
        <ProgressDiv>
          <Progress type="circle" percent={progress * 100} />
        </ProgressDiv>
      )}
      <Unity width="100%" height="100%" unityContent={unityContent} />
    </GameWrapper>
  );
});
```

**Expected behavior**
I want to properly quit my game and maybe even change page afterwards.

**Desktop (please complete the following information):**
 - OS: Windows or Linux
 - Browser chrome
 - Version 81

**Additional context**
Unity 2019.3.12f1

**Comment by darmane** [comment]
Hi! I'm having the same problem with Application.Quit().

unityContent.on("quitted", () => {
    console.log("QUITTING"); //This isn't even called after Application.Quit()
  });

Any ideas? thanks.

**Comment by jeffreylanters** [comment]
Seems related to https://github.com/elraccoone/react-unity-webgl/issues/22#issuecomment-680832404

**Comment by tarunspartan** [comment]
This helped me 

https://github.com/elraccoone/react-unity-webgl/issues/22#issuecomment-812828098

**Comment by tarunspartan** [comment]
This helped me 

https://github.com/elraccoone/react-unity-webgl/issues/22#issuecomment-812828098
