### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Hiverlab** [jeffreylanters/react-unity-webgl#104]
Hi is there a unitypackage for this?

In the first step of the installation, where can i find this file called npm to run this command line?
$ npm install react-unity-webgl

**Comment by jeffreylanters** [comment]
I think you've mixing up some things. Npm is the package manager needed to install modules such as react. This is meant for the web-app-side of your project. There is no Unity Packages, all you have to do is create an JSLib file IF you want to communicate between to the two. If there is no communication needed, there is nothing you have to do to prepare your Unity project, you can just create a WebGL build.

**Comment by Hiverlab** [comment]
Thanks for the fast reply!

In my jslib, where does the ReactUnityWebGL class come from?
When my jslib calls ReactUnityWebGL.LoadContentData(), the web app side says LoadContentData undefined even though the function is already written there. What did i missed?
