### ISSUE TITLE
Event handler for Unity Events is global

### ISSUE THREAD

**Issue by stefanb2** [jeffreylanters/react-unity-webgl#109]
**Describe the bug**
In our application we have two Unity WebGL components, out of which max one is visible at a time. Both components share a code base, e.g. they both send the `UnityEventDispatch` Unity Event to pass events to the React side. After calling
```js
this.unityContent.on('UnityEventDispatch', this.unityEventDispatch)
```
in the instance constructor only one of the event handlers is ever called.

**To Reproduce**

ReactUnityWebGL.jslib:

```js
mergeInto(LibraryManager.library, {
  ...
  UnityEventDispatch: function(json) {
    ReactUnityWebGL.UnityEventDispatch(Pointer_stringify(json));
  },
  ...
});
```

WebGLBridge.cs:
```cs
...
using UnityEngine;
using System.Runtime.InteropServices;
...

public static class WebGLBridge
{
  // These are defined as JS plugins at Assets/Plugin/ReactUnityWebGL.jslib
  ...
  [DllImport("__Internal")]
  private static extern void UnityEventDispatch(string json);
  ...
  public static void SendExternalEvent(string eventName, ...)
  {
    var data = ... // create some object that .ToString() converts to JSON string
    ...
    string json = data.ToString();
    UnityEventDispatch(json);
  }
}
```

UnityWrapper.js (React side)

```js
export default class UnityWrapper extends Component {
  ...
  constructor(props) {
    ...
    this.unityContent = new UnityContent(this.configPath, this.unityLoader);
    ...
    this.unityContent.on('UnityEventDispatch', this.unityEventDispatch);
    ...
  }
  ...
  unityEventDispatch = data => {
    // parse JSON, forward event to callback and so on...
  };
  ...
}
```

When Unity Component 1 calls `WebGLBridge.SendExternalEvent()` then the event handler on the `UnityContent` instance for the **other** component is called. I didn't verify this, but I think that this depends on the order of instance creation, i.e. the last created `UnityContent` will override the event handler for the same event of a previous `UnityContent` instance.

**Expected behavior**
When Unity Component 1 calls `WebGLBridge.SendExternalEvent()` then the event handler for its `UnityContent` instance will be called.

**Desktop**
 - OS: Linux
 - Browser: Chromium
 - Version: 84
 - JSON from component build output: `unityVersion: "2019.3.5f1"`
 - package.json: `"react-unity-webgl": "^7.1.10",`

**Comment by jeffreylanters** [comment]
Hi Stefan, thank you for opening an issue.

The module supports running multiple instances of a Unity application. But this is a slightly different case, since you're running the same Unity application twice. When using the Unity to React communication each instance should have their own event names.

Since the JSLib file doesn't know anything about the instances of the React component. When defining an event listener in React, event listeners with the same event name will be overwritten. A quick solution would be to let your Unity application send some kind of identifier, so you can later check this identifier in order to tell which Unity application instance did send it.

I hope this helps you with your implementation.

**Comment by stefanb2** [comment]
I guess my text may have beenmisleading.

We are running two **separate** Unity WebGL components, i.e. 2 separate builds,  2 different game objects, 2 instances of `UnityContent`. The only thing they share is a source code base for common code.

But if I understand your comment correctly if two components use the same Unity Event name, that one would be shared on the React side.

This behaviour should be documented IMHO.

**Comment by stefanb2** [comment]
The proposed changes fix the issue in our project, i.e. if you have multiple `UnityContent` instances that register an event handler for the same event name then all event handlers will be called.
