### ISSUE TITLE
Missing function js error

### ISSUE THREAD

**Issue by CineTek** [jeffreylanters/react-unity-webgl#11]
I can't seem to get function calls from within Unity to work with the outside React environment.

Just using the "OpenMenu" example code right now I get the following error on my page:
"Missing function: OpenMenu"
Even trying out empty functions does not work

Sending messages from React to Unity works without any problems though. 

Unity Version: 2017.3.0f1

**Comment by jeffreylanters** [comment]
Hey, could you please try `Application.CallExternal()` and check if that works for you? In the meantime I look into it.

**Comment by CineTek** [comment]
I'll try

**Comment by CineTek** [comment]
Application.ExternalCall() works

**Comment by CineTek** [comment]
Has this been fixed yet? ExternalCall is still deprecated and really weird to handle if you have to put every argument into an array when dealing with multiple parameters for example...

**Comment by jeffreylanters** [comment]
Not yet, I'm looking into this at the moment.

**Comment by jeffreylanters** [comment]
I published a fix in version [6.3.0](https://github.com/jeffreylanters/react-unity-webgl/releases/tag/6.3.0). Can you confirm if this works for you? Also see the updated [Read me](https://github.com/jeffreylanters/react-unity-webgl/tree/6.3.0#calling-javascript-functions-within-react-from-unity-scripts).

**Comment by meds** [comment]
Looks like it works now :)

**Comment by jeffreylanters** [comment]
Thanks for testing @meds!

**Comment by Syndicist** [comment]
I'm getting the same exact error as the OP on Unity 2019.1.11f1. Does the Assets folder need to be in a particular location for this to work? That's the only ambiguous part as far as I can tell.
