### ISSUE TITLE
Unity 2020 Unity Loader Error Handler

### ISSUE THREAD

**Issue by jeffreylanters** [jeffreylanters/react-unity-webgl#116]
**Describe the bug**
In Unity 2017 to 2019, the Unity Loader generated by Unity used to expose a hook which would invoke when any kind of error was thrown from the Unity Loader or Unity Player itself. Even error during the Runtime of your application. This hook has been removed in Unity 2020. 

The removal has not been documented, and I cannot seem the find any clue of where the event handler has good. It is hard to believe they haven't added any other kind of error handler.

**To Reproduce**
1. Make a Unity WebGL build with an intensional runtime error
2. Open the html file generated by Unity
3. Try to catch the runtime error using a hook

**Screenshots**
[The code in 7.x.x with the Unity 2019 error handler](https://github.com/elraccoone/react-unity-webgl/blob/7174b9e7b3a535b40d9e46caaafcd690b9e695ff/source/components/Unity.ts#L107)
[The interface based on the Unity Loader showing the error handler](https://github.com/elraccoone/react-unity-webgl/blob/7174b9e7b3a535b40d9e46caaafcd690b9e695ff/source/declarations/UnityLoader.ts#L19)

**Additional context**
If anyone happens to know how to handle error events in Unity 2020, especially Runtime errors. Please feel free to reply on this thread.

**Comment by DorianGrey** [comment]
If I spotted this correctly, this code is used to handle any kind of errors:
```javascript
  function errorHandler(message, filename, lineno) {
    if (Module.startupErrorHandler) {
      Module.startupErrorHandler(message, filename, lineno);
      return;
    }
    if (Module.errorHandler && Module.errorHandler(message, filename, lineno))
      return;
    console.log("Invoking error handler due to\n" + message);
    if (typeof dump == "function")
      dump("Invoking error handler due to\n" + message);
    // Firefox has a bug where it's IndexedDB implementation will throw UnknownErrors, which are harmless, and should not be shown.
    if (message.indexOf("UnknownError") != -1)
      return;
    // Ignore error when application terminated with return code 0
    if (message.indexOf("Program terminated with exit(0)") != -1)
      return;
    if (errorHandler.didShowErrorMessage)
      return;
    var message = "An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was:\n" + message;
    if (message.indexOf("DISABLE_EXCEPTION_CATCHING") != -1) {
      message = "An exception has occurred, but exception handling has been disabled in this build. If you are the developer of this content, enable exceptions in your project WebGL player settings to be able to catch the exception or see the stack trace.";
    } else if (message.indexOf("Cannot enlarge memory arrays") != -1) {
      message = "Out of memory. If you are the developer of this content, try allocating more memory to your WebGL build in the WebGL player settings.";
    } else if (message.indexOf("Invalid array buffer length") != -1  || message.indexOf("Invalid typed array length") != -1 || message.indexOf("out of memory") != -1 || message.indexOf("could not allocate memory") != -1) {
      message = "The browser could not allocate enough memory for the WebGL content. If you are the developer of this content, try allocating less memory to your WebGL build in the WebGL player settings.";
    }
    alert(message);
    errorHandler.didShowErrorMessage = true;
  }
```
This is part of the `.loader.js` file generated in 2020. The mentioned `Module` variable becomes attached to the `unityInstance`.
The `startUpErrorHandler` becomes overridden automatically during the startup process here:
```javascript
  return new Promise(function (resolve, reject) {
    if (!Module.SystemInfo.hasWebGL) {
      reject("Your browser does not support WebGL.");
    } else if (!Module.SystemInfo.hasWasm) {
      reject("Your browser does not support WebAssembly.");
    } else {
      Module.startupErrorHandler = reject;
      onProgress(0);
      Module.postRun.push(function () {
        onProgress(1);
        delete Module.startupErrorHandler;
        resolve(unityInstance);
      });
      loadBuild();
    }
  });
```
If no `errorHandler` is registered, an `Alert` is triggered.

It seems that the `errorHandler` can only be registered after the init phase, i.e. startup errors still cause a hard rejection on the init phase.

Unluckily, the code also registers two event handlers on global level:
```
window.addEventListener("error", errorListener);
window.addEventListener("unhandledrejection", errorListener);
```
Results from both are forwarded to the error handler (in case there is any) even if the particular errors are not caused by Unity.

I'm not entirely sure about errors triggered from the compiled WASM code, though.
