### ISSUE TITLE
Best way to test application

### ISSUE THREAD

**Issue by allenWTF** [jeffreylanters/react-unity-webgl#119]
Hello! I want to try this amazing package but i have one question. Sorry if it's off-top. 

What is the best way to test communication between React and Unity WebGL apps (or even just to test Unity WebGL only)? Because there is only one that comes to my mind which is to generate a new WebGL build everytime something changes. But WebGL build takes so long that it's pretty much impossible to have a normal development workflow.

Maybe I'm missing something? Thanks in advance!

**Comment by jeffreylanters** [comment]
Hi! Thank you very much, for beginners I recommend looking at the [React-Unity-WebGL-Test](https://github.com/jeffreylanters/react-unity-webgl-test) repository.
