### ISSUE TITLE
Allow setting of Unity canvas element id

### ISSUE THREAD

**Issue by stefanb2** [jeffreylanters/react-unity-webgl#124]
**Is your feature request related to a problem? Please describe.**
In API >= 8 the canvas element no longer has an id and there is no way to set it.

**Describe the solution you'd like**
Add an `id=` prop to the Unity component:
~~~jsx
<Unity id="..." unityContext={...} />
~~~

**Describe alternatives you've considered**
You can already set the class name of the Unity canvas element, i.e. you can use `event.target.classList.contains(...)` to identify it. But IMHO `event.target.id === '...'` is much more concise.

Test automation may also benefit from this feature.

**Additional context**
An alternative would be to add a `canvasProps=` prop which would allow the user to set other properties on the canvas element, i.e.
~~~jsx
<Unity
  canvasProps={{
    id: '...',
  }}
  unityContext={...}
/>
~~~

**Comment by flxwu** [comment]
Hi, any update here?

**Comment by jeffreylanters** [comment]
Hi. This literal feature is not implemented. However, it is still possible to get a reference to the canvas and thus its id.

See the documentation for further details

https://react-unity-webgl.dev/docs/api/canvas-ref
