### ISSUE TITLE
Dynamic build url from the server 

### ISSUE THREAD

**Issue by Gardens18** [jeffreylanters/react-unity-webgl#125]
Greetings, 

Can I put the below files  ( such as myunityapp.loader.js, myunityapp.data, myunityapp.framework.js, myunityapp.wasm ) in the external server instead of packaging with the app itself, so that we could change the configuration of the unity project any time dynamically.

this.unityContext = new UnityContext({
      loaderUrl: "build/myunityapp.loader.js",
      dataUrl: "build/myunityapp.data",
      frameworkUrl: "build/myunityapp.framework.js",
      codeUrl: "build/myunityapp.wasm"
    });

**Comment by jeffreylanters** [comment]
Hi, short: yes. This module does NOT add any of the files above to your javascript bundle, they will be loaded during runtime. Which means you can provide external URL's.
