### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by lint12** [jeffreylanters/react-unity-webgl#126]
Hi, I am trying to use a production build which has .gz files for the dataUrl, frameworkUrl, and codeUrl in order to load up the content faster on my website. However it seems like the library is having a hard time creating an instance of unity context model with those files. Is it possible to make it work with compressed files? 

This is what I have originally: 
<img width="444" alt="Screen Shot 2020-10-22 at 6 27 16 PM" src="https://user-images.githubusercontent.com/46506664/96936516-37dedd80-1494-11eb-95bf-59856326baad.png">

But I want it to work with .gz files like these: 
<img width="449" alt="Screen Shot 2020-10-22 at 6 28 30 PM" src="https://user-images.githubusercontent.com/46506664/96936609-63fa5e80-1494-11eb-962b-b0b261ccef4e.png">

**Comment by jeffreylanters** [comment]
Hi. Configuration for GZipping is done on your server's side, this has nothing to do with this module. -- What kind of server are you using?

**Comment by lint12** [comment]
We are using Firebase for the backend.

**Comment by zmays** [comment]
Make sure to set the headers correctly on the server for all the assets: 

```
				'Content-Encoding': 'gzip',
				'Content-Type': 'application/js',
```

e.g for wasm would be application/wasm

**Comment by zmays** [comment]
For others using s3, here is an example node script for uploading your game assets:

```
import S3, { ClientConfiguration } from 'aws-sdk/clients/s3'
import { Credentials } from 'aws-sdk/lib/core'
import fs from 'fs'
import dotenv from 'dotenv'

async function run () {
	dotenv.config()
	const credentials = new Credentials({
		accessKeyId: process.env.ACCESS_KEY_ID,
		secretAccessKey: process.env.SECRET_ACCESS_KEY,
	})
	const region = process.env.S3_REGION
	const s3Config: ClientConfiguration = {
		region,
		credentials,
	}
	const s3 = new S3(s3Config)
	const relPath = '../ville/builds/v2/Build/'
	const data = fs.readFileSync(relPath + 'v2.data.gz')
	const framework = fs.readFileSync(relPath + 'v2.framework.js.gz')
	const loader = fs.readFileSync(relPath + 'v2.loader.js')
	const wasm = fs.readFileSync(relPath + 'v2.wasm.gz')

	await s3
		.putObject({
			Bucket: 'euda-game-assets',
			Key: 'v1/v2.data.gz',
			Body: data,
			ContentType: 'application/data',
			ContentEncoding: 'gzip',
		})
		.promise()
	await s3
		.putObject({
			Bucket: 'euda-game-assets',
			Key: 'v1/v2.framework.js.gz',
			Body: framework,
			ContentEncoding: 'gzip',
			ContentType: 'application/js',
		})
		.promise()
	await s3
		.putObject({
			Bucket: 'euda-game-assets',
			Key: 'v1/v2.loader.js',
			Body: loader,
			ContentType: 'application/js',
		})
		.promise()
	await s3
		.putObject({
			Bucket: 'euda-game-assets',
			Key: 'v1/v2.wasm.gz',
			Body: wasm,
			ContentEncoding: 'gzip',
			ContentType: 'application/wasm',
		})
		.promise()
}

run()
	.then(() => console.log('done'))
	.catch(console.error)

```

**Comment by dongillett** [comment]
Thanks to everyone's comments... saved me a ton of time to figure out.  Here are aws scripts to do it if you want a command line option.

**Comment by dongillett** [comment]
Has anyone noticed that when serving from S3 the content is never re-loaded from local cache?  It's always re-downloaded. I don't know if another metadata value needs to get set on the files to enable local caching but am investigating that.

**Comment by jeffreylanters** [comment]
> Has anyone noticed that when serving from S3 the content is never re-loaded from local cache?  It's always re-downloaded. I don't know if another metadata value needs to get set on the files to enable local caching but am investigating that.

This behavior is based on your server's configuration. Could you check the file's response cache headers?

**Comment by dongillett** [comment]
@jeffreylanters thanks for the reply.  It didn't have a cache header so I added one.  Here is what is returned now... but it has the same behavior of re-downloading on every reload.
Cache-Control: max-age=604800

**Comment by goqa-dev** [comment]
> We are using Firebase for the backend.

did you manage to get this working?
