### ISSUE TITLE
Configuration Problem 

### ISSUE THREAD

**Issue by zalven** [jeffreylanters/react-unity-webgl#131]
I have a file called like this.
![image](https://user-images.githubusercontent.com/49342212/98461799-21ea5000-21ea-11eb-91bf-30afe68f6546.png)
How do I implement them inside react? I'm having a hard time figuring that out.

**Comment by jeffreylanters** [comment]
Hi! The [Test Repository](https://github.com/jeffreylanters/react-unity-webgl-test) might help you out.

**Comment by rvrjp7** [comment]
@zalven, did you find any solution for this? I'm facing the same issue.

**Comment by zalven** [comment]
@rvrjp7 @jeffreylanters  Not yet, I'm solving it today. It's kinda foggy to me when I read the test repository because we don't have the same file type like mine where there's ".unitywebfile". Like should I rename those? 
At first, I'm testing the build player settings from unity. Sadly it didn't work T-T

**Comment by rvrjp7** [comment]
@zalven, Same here, test file includes "UnityContent" which is not available in the latest version which uses Unitycontext.
 I'm also working on it, If you find any fix first, then please add it here. I'll do the same if anything works 👍

**Comment by rvrjp7** [comment]
@zalven, which Unity version you are using? 2019 or 2020?

**Comment by zalven** [comment]
I'm using 2019 btw. Please message or email me if you already solved it and I'll do the same. Thank you!

**Comment by rvrjp7** [comment]
As mentioned in the [homepage](https://www.npmjs.com/package/react-unity-webgl), use "npm install react-unity-webgl@7.x" for Unity 2018 and 2019 (LTS) ,
and use following code to render unity game :
```
import Unity, { UnityContent } from "react-unity-webgl";
export default function App() {
    let unityContent = new UnityContent(
        "Build/Build.json",
        "Build/UnityLoader.js"
    );
    unityContent.on("progress", progressionVal => {
        console.log("wip")
    });
    return (
        <div><Unity unityContent={unityContent} /></div>
    );
}
```

**Comment by VegetableThins** [comment]
> 
> 
> As mentioned in the [Homepage](https://www.npmjs.com/package/react-unity-webgl), use `npm install react-unity-webgl@7.x` for Unity 2018 and 2019 (LTS) ,
> and use following code to render unity game :
> 
> ```
> import Unity, { UnityContent } from "react-unity-webgl";
> export default function App() {
>     let unityContent = new UnityContent(
>         "Build/Build.json",
>         "Build/UnityLoader.js"
>     );
>     return (
>         <div><Unity unityContent={unityContent} /></div>
>     );
> }
> ```



> 
> 
> As mentioned in the [Homepage](https://www.npmjs.com/package/react-unity-webgl), use `npm install react-unity-webgl@7.x` for Unity 2018 and 2019 (LTS) ,
> and use following code to render unity game :
> 
> ```
> import Unity, { UnityContent } from "react-unity-webgl";
> export default function App() {
>     let unityContent = new UnityContent(
>         "Build/Build.json",
>         "Build/UnityLoader.js"
>     );
>     return (
>         <div><Unity unityContent={unityContent} /></div>
>     );
> }
> ```

This worked for me! also helped to know that the build path was relative to your index.html . Thanks a lot you saved me!

**Comment by dharry1968** [comment]
Hi, iv'e been trying to get this to work, using Unity 2019.4.x so have installed @7.x but I keep getting an error I don't understand. My folder/file structure is: 
![image](https://user-images.githubusercontent.com/790458/101768156-5464d100-3b39-11eb-8c6a-56be09292b23.png)

and my index.js is: 

import React from "react";
import Unity, { UnityContent } from "react-unity-webgl";

export default function App() {
    let unityContent = new UnityContent(
        "Build/Web.json",
        "Build/UnityLoader.js"
    );
    return (
        <div><Unity unityContent={unityContent} /></div>
    );
}

But it is telling me: http://dg.darkgalaxies.io:3000/Build/UnityLoader.js 404 (Not Found)

I have tried the path with ./Build and ../Build but still nothing. I am using Babel and Next, not sure if that makes a difference?

Any pointers you can help me with?

Thanks
Dean

**Comment by jeffreylanters** [comment]
Hi Dean, your Unity build should not be in your source directory. When building your React app, see where it's being distributed to. This is the directory where your Unity build's path is relative from.

**Comment by dharry1968** [comment]
Thanks Jeffrey, iv'e been running the site in dev mode whilst I keep putting it together so I thought that path was correct for a dev build. I have built it now for production and it builds to the build directory, but i'm not really sure where I should be putting the Unity content... sorry, i'm quite new to React so trying to get my head around it all...

**Comment by SeanGephardt1** [comment]
> > As mentioned in the [Homepage](https://www.npmjs.com/package/react-unity-webgl), use `npm install react-unity-webgl@7.x` for Unity 2018 and 2019 (LTS) ,
> > and use following code to render unity game :
> > ```
> > import Unity, { UnityContent } from "react-unity-webgl";
> > export default function App() {
> >     let unityContent = new UnityContent(
> >         "Build/Build.json",
> >         "Build/UnityLoader.js"
> >     );
> >     return (
> >         <div><Unity unityContent={unityContent} /></div>
> >     );
> > }
> > ```
> 
> > As mentioned in the [Homepage](https://www.npmjs.com/package/react-unity-webgl), use `npm install react-unity-webgl@7.x` for Unity 2018 and 2019 (LTS) ,
> > and use following code to render unity game :
> > ```
> > import Unity, { UnityContent } from "react-unity-webgl";
> > export default function App() {
> >     let unityContent = new UnityContent(
> >         "Build/Build.json",
> >         "Build/UnityLoader.js"
> >     );
> >     return (
> >         <div><Unity unityContent={unityContent} /></div>
> >     );
> > }
> > ```
> 
> This worked for me! also helped to know that the build path was relative to your index.html . Thanks a lot you saved me!

The home states "UnityContext" instead of "UnityContent". Making this change to "UnityContent" got my Unity WebGL build working in a React app.

**Comment by jeffreylanters** [comment]
Hi @SeanGephardt1. The "UnityContent" has been reworked into "UnityContext" from version 7.x to 8.x. You can utilise the current readme for 8.x documentation, or head over to the [legacy documentation](https://github.com/elraccoone/react-unity-webgl/tree/master/.github/LEGACY_DOCUMENTATION) for 7.x if you're getting lost. Best of luck with your project! If you need any help, feel free to open a new discussion.

**Comment by SeanGephardt1** [comment]
> Hi @SeanGephardt1. The "UnityContent" has been reworked into "UnityContext" from version 7.x to 8.x. You can utilise the current readme for 8.x documentation, or head over to the [legacy documentation](https://github.com/elraccoone/react-unity-webgl/tree/master/.github/LEGACY_DOCUMENTATION) for 7.x if you're getting lost. Best of luck with your project! If you need any help, feel free to open a new discussion.

Thanks!

**Comment by N7Pankake** [comment]
> > Hi @SeanGephardt1. The "UnityContent" has been reworked into "UnityContext" from version 7.x to 8.x. You can utilise the current readme for 8.x documentation, or head over to the [legacy documentation](https://github.com/elraccoone/react-unity-webgl/tree/master/.github/LEGACY_DOCUMENTATION) for 7.x if you're getting lost. Best of luck with your project! If you need any help, feel free to open a new discussion.
> 
> Thanks!

The legacy documentation no longer exist it says 404 error, also I'm having the same issue and I can't understand why it doesn't work because I have it on my public folder.

This is how I have my folder structure

![image](https://user-images.githubusercontent.com/8898953/148269725-a9e6337f-1823-467f-b2ba-49f0880936ca.png)

And this is what I have in my JS file where I'm trying to render the Unity project 

```
import React from 'react'
import Unity, { UnityContent } from "react-unity-webgl";

let unityContent = new UnityContent(
  "Megaman/Build/Megaman.json",
  "Megaman/Build/UnityLoader.js"
);

function MegamanGame() {
    return (
        <div><Unity unityContent={unityContent} /></div>
      
    )
}

export default MegamanGame
```

**Comment by jeffreylanters** [comment]
@N7Pankake The legacy documentation moved to the readme under the 7.x tag. You should be able to find it there. 

Looking at your screenshot, your structure and React code looks just fine. Are you getting any errors in the console?

**Comment by N7Pankake** [comment]
Oh wow how could I forget to check my console ...

![image](https://user-images.githubusercontent.com/8898953/148281998-7b7e818b-09f7-4bc8-a779-8953764b640b.png)

**Comment by jeffreylanters** [comment]
Moved to #299
