### ISSUE TITLE
Trouble with getting started with SSR using NextJS

### ISSUE THREAD

**Issue by leskodan** [jeffreylanters/react-unity-webgl#139]
Hello, I am having trouble getting a simple Unity webgl project to render in my React page despite following the quick start instructions (as well as some instructions from the community). I am hoping someone can point out what I am doing wrong!

1. Creating a component for my Unity content (Viewer.js)
![image](https://user-images.githubusercontent.com/51446532/103386767-64cff200-4ace-11eb-87d7-8dff0962c137.png)
2. Importing into my index.js
![image](https://user-images.githubusercontent.com/51446532/103386800-892bce80-4ace-11eb-80c8-ec22261a6a4f.png)
3. With the following file structure:
![image](https://user-images.githubusercontent.com/51446532/103386835-b5474f80-4ace-11eb-8d88-78b8ee94e0f3.png)

But I am getting the following error:
![image](https://user-images.githubusercontent.com/51446532/103386849-c55f2f00-4ace-11eb-9d95-24b6b61cab7f.png)

Thanks in advance for any input!

**Comment by leskodan** [comment]
Forgot to mention that this is a Next.js app.

**Comment by manzinge** [comment]
Hey,

I'm not sure if this is how it is supposed to work.
Generating a new UnityContext is done with the following function (using UnityCONTEXT) (Same for the Html Tag)
![image](https://user-images.githubusercontent.com/43249083/103640146-cae5ca80-4f4f-11eb-8b13-a9f37bff7fce.png)
Can you please try that and report back if it worked?

Best
Max

**Comment by jeffreylanters** [comment]
Hi @leskodan, the module is currently not supporting server side rendering. I'm trying to look into it any time soon.

**Comment by jeffreylanters** [comment]
I will be working on the feature on a separate branch which can be monitored from #140. This PR might need testings in the future.

**Comment by leskodan** [comment]
Hi @jeffreylanters, that was what I expected, thanks for looking into this! I'm really happy with how this works in pure React, but excited to see it progress in the context of Next.js and server side rendering.

**Comment by jeffreylanters** [comment]
Thanks! I'll keep you posted, but I'm completely new to SSR so I have to take some crash courses and look into it. it might take a while before I publicly release support on NPM.

**Comment by leskodan** [comment]
Got it. I can try this on my end, but do suspect that using 'next export' to statically generate the HTML would work for the time being? As far as I understand, this is an alternative to SSR in Next.js.

**Comment by leskodan** [comment]
Update on my end:
```
<div>
        { process.browser && <UnityComponent/>}
</div>
```

Using the following code forces Next to use client side rendering for the Unity component. This serves as a workaround for the lack of support for SSR.

**Comment by clokk** [comment]
you are a lifesaver @leskodan . I have also been attempting to implement with Next js. Thank you jeffrey for a wonderful package!

**Comment by jeffreylanters** [comment]
Thanks @Clokk! I'm still planning on building this in, but I have to look into this first. I've never used server side rendering before. @Leskodan's example is a good start, but he's excluding the entire module from SSR. I want to try excluding it partially. If any of you have some tips let me know, or feel free to contribute.

**Comment by clokk** [comment]
Hi @jeffreylanters , really just started looking at this today - but from what I gathered I could not get SSR to work in production mode even with leskodan's fix. An alternative approach that I got working fairly quickly is to dump the files in an amazon s3 bucket, ensure that the files are public and properly set CORS. I have it working in production now with SSR. I just had to point UnityContent params to the new amazon urls rather than locally in public file path.

IMO you don't need to rush to this, especially when a solution as I have laid out exists with fairly easy implementation. Thanks again!

**Comment by JonMacPhers** [comment]
I'm having a hard time getting either of these solutions to work on my NextJS build. I'm also having a hard time determining exactly where my build is failing. I don't get any error messages in console and the UnityContext.on events don't seem to fire at all. It would be beautiful to get a NextJS example added to the ReadME

**Comment by JonMacPhers** [comment]
.....So after my build failing on Chrome for a couple days it turns out it's actually working on Brave? I realized this from cloning your template repo and noticing it only runs on my Brave browser as well (not Chrome). So for anyone else experiencing my issue I would recommend trying different browsers.
