### ISSUE TITLE
How to catch this errors

### ISSUE THREAD

**Issue by BostonLeeK** [jeffreylanters/react-unity-webgl#142]
I use Brotli and when for some reason container not loaded I want catch erros like this
Uncaught SyntaxError: Invalid or unexpected token
build.loader.js:1 Uncaught ReferenceError: unityFramework is not defined
    at HTMLScriptElement.r.onload (build.loader.js:1)

to render another content

unityContext.on('error' ... not catching this errors and unityContext.on('progress' stuck on 0.9.

Can I some how catch it with unityContext or i must check another services for this?

**Comment by jeffreylanters** [comment]
Hi! If you're still running into this problem, could you try again using the latest version? I've recently implemented a wider error boundary.
