### ISSUE TITLE
Unable to use the Unity Loader

### ISSUE THREAD

**Issue by fralps** [jeffreylanters/react-unity-webgl#145]
Hi guys 👋 

I know there has been multiple issues relating to this issue and the public path.

I installed the test repo correctly but when I start the project, I have this error:

![Capture d’écran 2021-02-09 à 10 08 25](https://user-images.githubusercontent.com/48285890/107341165-ec8e2080-6abe-11eb-9470-eb48c0c5f171.png)

Here my `package.json`:

<img width="290" alt="Capture d’écran 2021-02-09 à 10 08 50" src="https://user-images.githubusercontent.com/48285890/107341244-04fe3b00-6abf-11eb-9b30-473e8c98451c.png">

And my `UnityContent`:

<img width="341" alt="Capture d’écran 2021-02-09 à 10 09 20" src="https://user-images.githubusercontent.com/48285890/107341285-10e9fd00-6abf-11eb-88dc-d5a7cba19c36.png">

I am not able to fix my bug 🐛 😔 

Could you please help me or explain to me what I missing ? 🙏

**Comment by jeffreylanters** [comment]
Hi. Can you show me your directory architecture.

**Comment by fralps** [comment]
<img width="231" alt="Capture d’écran 2021-02-09 à 13 12 01" src="https://user-images.githubusercontent.com/48285890/107361966-70a0d200-6ad8-11eb-8e49-dc82ba126cf2.png">

**Comment by jeffreylanters** [comment]
Can you try `/build/...` instead of `build/...`?

**Comment by jeffreylanters** [comment]
If that's not working can you start your webapp and try to navigate to the framework.js file Unity generated manually using the address bar to see if it's reachable at all?

**Comment by fralps** [comment]
I got a `304 not modified`
