### ISSUE TITLE
A problem occurred while mounting Unable to load ./Build/Build.loader.js

### ISSUE THREAD

**Issue by gabrielcassimiro** [jeffreylanters/react-unity-webgl#182]
Even though I follow the documentation, when I try to run the project this error occurs.
`unity.js:159 A problem occurred while mounting Unable to load ./Build/Buildv2.loader.js [object Event]`
`GET http://localhost:3000/user/play/Build/Buildv2.loader.js net::ERR_ABORTED 404 (Not Found)`
and the project doesn't run.

**Comment by jeffreylanters** [comment]
What version of the module are you using?

**Comment by jeffreylanters** [comment]
Your build should be available from the browser so the module can access it. See [the documentation](https://github.com/jeffreylanters/react-unity-webgl#creating-a-unity-context-object) for more details.

**Comment by jeffreylanters** [comment]
It also seems related to #57

**Comment by jeffreylanters** [comment]
No problem. Let me know if you're getting it to work.

**Comment by jeffreylanters** [comment]
Awesome! Best of luck with your project.
