### ISSUE TITLE
Cannot load Unity5 WebGL builds

### ISSUE THREAD

**Issue by ruizj-ibm** [jeffreylanters/react-unity-webgl#19]
```
Uncaught (in promise) ReferenceError: UnityLoader is not defined
    at Unity.js:68
    at <anonymous>
```

Unity 5 does not generate a WebGL.json file.  The code is placed into the index.html file into var Module.

There is also the issue of the gzipped files for Release builds.  Not sure if its possible to handle those.

**Comment by jeffreylanters** [comment]
Hi @ruizj-ibm, this module is compatible with Unity 5.6 or newer and Unity 2017 or newer. You can try upgrading your project to the latest version of Unity.
