### ISSUE TITLE
The state of monitoring Unity loading is not correct

### ISSUE THREAD

**Issue by ZHSC17** [jeffreylanters/react-unity-webgl#196]
**Describe the bug**
Now the plug-in monitors the completion of Unity loading by monitoring progress, but Unity creates unityInstance after setting the value of progress to 1.

**To Reproduce**
 Unity:
```js
Module.postRun.push(function () {
  onProgress(1);
  delete Module.startupErrorHandler;
  resolve(unityInstance);
});
```

react-unity-webgl:
```js
Unity.prototype.onProgress = function (progression) {
  this.unityContext.dispatchEventListener("progress", progression);
  if (progression === 1) {
    this.unityContext.dispatchEventListener("loaded");
    if (typeof this.htmlCanvasElementReference !== "undefined")
      this.unityContext.dispatchEventListener("canvas", this.htmlCanvasElementReference);
  }
};
```

**Expected behavior**
If you send a message while listening to the loaded state of react-unity-webgl, it will fail because of unityInstance undefined

**Comment by jeffreylanters** [comment]
Hello, I'm not quite sure if I understand what you mean. Could you provide a complete example? Thanks!
