### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by jollyland** [jeffreylanters/react-unity-webgl#203]
Hello Jeffery, so I received the same issue while putting my unity project into react project
![image](https://user-images.githubusercontent.com/57451574/121896046-74c55080-cd53-11eb-9dfd-3e2d8c4ba2f9.png)

I've tried the solution #57 and #147 provided, but it still not working
Here's my file trees
![image](https://user-images.githubusercontent.com/57451574/121896452-e1404f80-cd53-11eb-8f1a-84a4f17b887f.png)

I would appreciate your help, Thanks :) !

**Comment by jeffreylanters** [comment]
Hi. Don't use spaces in your file names, web browsers and servers cannot handle these properly. The best practice in web development is to use dashes and keep everything that's being served lowercase.

**Comment by jollyland** [comment]
> Hi. Don't use spaces in your file names, web browsers and servers cannot handle these properly. The best practice in web development is to use dashes and keep everything that's being served lowercase.
Thank you for response rapidly,I re-export whole project from unity again with lowercase, but the issue still exist
![image](https://user-images.githubusercontent.com/57451574/121905475-c58d7700-cd5c-11eb-8b88-12913582b700.png)

**Comment by jeffreylanters** [comment]
Looking at your hierarchy, the following should work. Can you try this?

```js
import React from "react";
import Unity, { UnityContext } from "react-unity-webgl";

const unityContext = new UnityContext({
  loaderUrl: "/build/seeatraitv1.loader.js",
  dataUrl: "/build/seeatraitv1.data",
  frameworkUrl: "/build/seeatraitv1.framework.js",
  codeUrl: "/build/seeatraitv1.wasm",
});

function App() {
  return <Unity unityContext={unityContext} />;
}
```

**Comment by jollyland** [comment]
I'm not sure which part get wrong/right, but it ends up working!
Appreciate for the replies and the package! 
It's so relived finding that developer is still maintaining/updating the package, thank you so much for this diligent work!

**Comment by jeffreylanters** [comment]
I'm not sure what your configuration was before, but I added slashes to the beginning of each URL on purpose so the module will try to load these files relative from the base URL rather than relative from the current location.

You're welcome. Best of luck with your project!
