### ISSUE TITLE
react-unity-webgl issue : A problem occurred while mounting abort({}) at ERROR 

### ISSUE THREAD

**Issue by chan27-2** [jeffreylanters/react-unity-webgl#206]
### WebGL unity build is not working in the hosted site (AWS amplify) but working in **development mode**.
```
A problem occurred while mounting abort({}) at Error
    at jsStackTrace (https://....com/build/game/game.framework.js:2:16316)
    at stackTrace (https://...com/build/game/game.framework.js:2:16487)
    at abort (https://....com/build/game/game.framework.js:2:748)
    at https://....com/build/game/game.framework.js:2:25337
```
![Screenshot 2021-06-23 at 5 15 08 PM](https://user-images.githubusercontent.com/63861979/123091104-922aa680-d446-11eb-97a9-526f03defd50.jpg)

This is unity.ts:104 where its showing an error
![Screenshot 2021-06-23 at 6 15 23 PM](https://user-images.githubusercontent.com/63861979/123098647-fbaeb300-d44e-11eb-8bc4-f73c4dea2ad1.jpg)

in package.json
added `"react-unity-webgl": "^8.4.2"`

@jeffreylanters

**Comment by jeffreylanters** [comment]
Hi! Since the error is thrown by `game.framework.js`, I assume this is a problem with your Unity build. Does it run locally? Are you sure the path the build is correct when visiting via AWS? Could you send a screenshot of the network tab?
