### ISSUE TITLE
TypeScript error TS1005

### ISSUE THREAD

**Issue by PanosParalakis** [jeffreylanters/react-unity-webgl#215]
Typescript throws an error when trying to use the library with minimum configuration. Problems seems to live inside `IUnityContextEventMap` interface. 

Possible solution could be: 
```
progress: [number];
```

**Describe the bug**
TypeScript error in  node_modules/react-unity-webgl/distribution/interfaces/unity-context-event-map.d.ts(15,27):
',' expected.  TS1005

    13 |      * hit 1. The event will invoke everytime the progression advances.
    14 |      */
  > 15 |     progress: number;
       |                           ^
    16 |     /**
    17 |      * While your application is being downloaded from the server and loaded into
    18 |      * memory, you might want to display some sort of overlay or loading screen.

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - React Unity WebGL Version: [e.g. 8.0.0]  8.4.6
 - Browser: [e.g. stock browser, safari 10.1] Chrome latest
 - NodeJS Version: [e.g. 12.0.0]  v14.17.0
 - Typescript version: 3.9.9
 - React version: 16.14.0

**Comment by ttakuya50** [comment]
@PanosParalakis 
I ran into the same error and solved it, so I'll share
I changed the typescript version to 4.3.5 and the error went away!
I hope you can find a solution too.
