### ISSUE TITLE
Issues loading Addressables from remote location

### ISSUE THREAD

**Issue by junniepat** [jeffreylanters/react-unity-webgl#216]
While trying to load in addressables i get this error.
I also noticed my streaming assets are not going to the root folder.

Below is a picture of the error i am getting.

![image](https://user-images.githubusercontent.com/3358365/127870264-a726a67c-2b29-4270-a580-e3327430ae17.png)

**Comment by jeffreylanters** [comment]
Can you share a snippet of your implementation?
