### ISSUE TITLE
UnityContent is not a constructor on `gatsby build`, v7.x

### ISSUE THREAD

**Issue by blakermchale** [jeffreylanters/react-unity-webgl#229]
**Describe the bug**
I'm trying to build a website with a unity game from 2019 inside it. For this website I am using Gatsby with React and Typescript. I'm able to build a development version with `gatsby develop` fine. However, once I run `gatsby build` it says:
```
Building static HTML failed for path "/projects/planetpolluter/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


   9 | const UnityPlanetPolluter = () => {
  10 |     // @ts-ignore
> 11 |     const unityContent = new UnityContent(
     |                          ^
  12 |         unityBuildJson, unityLoaderJs
  13 |     );
  14 |     return (


  WebpackError: TypeError: react_unity_webgl__WEBPACK_IMPORTED_MODULE_1__.UnityContent is not a constructor
```

Here's the code I'm using:
```
import React from 'react';
import Unity, { UnityContent } from "react-unity-webgl";

const unityBuildPath = "/data/planetpolluter/PlanetPolluterBuild/";
const unityBuildJson = unityBuildPath + "PolluterWeb.json";
const unityLoaderJs = unityBuildPath + "UnityLoader.js";

const UnityPlanetPolluter = () => {
    // @ts-ignore
    const unityContent = new UnityContent(
        unityBuildJson, unityLoaderJs
    );
    return (
        <Unity unityContent={unityContent} />
    );
}
```

**To Reproduce**
1. Build a project with Unity 7.x and Gatsby

**Expected behavior**
To build and generate a website.

**Screenshots**

**Details (please complete the following information):**
 - React Unity WebGL Version: 7.x
 - Device and OS: Dell XPS 15 and Windows 10
 - Browser: n/a
 - NodeJS Version: v14.17.5
 - Bundler: webpack (used by Gatsby)

**Additional context**
N/A

**Comment by jeffreylanters** [comment]
Sorry, I cannot help you with Gatsby specific problems. I'll leave this open for anyone else who might be able to help you. The only thing I can think of is, are you sure Gatsby is installing the right version of the module? Since `UnityContent` has been refactored to `UnityContext` in version 8.x.

**Comment by blakermchale** [comment]
I checked `node_modules` and my version is `7.1.13`. The strange thing is I am able to run the app when testing with a development server through `gatsby develop`. To my understanding `gatsby build` doesn't have access to a browser when building unlike develop.

Here's a link to my repository on the `gatsby` branch in case anyone wants to try building it.

**Comment by blakermchale** [comment]
I just found a solution. You need to construct `UnityContent` after the component is mounted. I did this by using the hook `useEffect()`. You have to handle the case where the component is null since that's its state prior to mounting. Here's my working code:
```
import React from 'react';
import Unity, { UnityContent } from "react-unity-webgl"

const unityBuildPath = "/data/planetpolluter/PlanetPolluterBuild/";
const unityBuildJson = unityBuildPath + "PolluterWeb.json";
const unityLoaderJs = unityBuildPath + "UnityLoader.js";

const UnityPlanetPolluter = () => {
    const [unityContent, setUnityContent] = React.useState(null);
    React.useEffect(() => {
        setUnityContent(new UnityContent(
            unityBuildJson, unityLoaderJs
        ));
    })
    if (unityContent == null) {
        return (<>
        <h4>
             Unity is not working yet.
        </h4>
        </>);
    }
    else {
        return (
            <Unity unityContent={unityContent} />
            
        );
    }
}

export default UnityPlanetPolluter;
```
