### ISSUE TITLE
Module somehow disables text inputs?

### ISSUE THREAD

**Issue by MitchEff** [jeffreylanters/react-unity-webgl#23]
I'm really confused by this one. In my project, as soon as a <Unity /> module is included (stock settings, nothing fancy), I can no longer control any text inputs - I can't even press left and right to move the carets. 

I've isolated this just to this module - everything goes back to normal as soon as it's removed. 

Has anyone seen this before?

**Comment by jeffreylanters** [comment]
No, I've never seen this before. I assume you mean HTML input fields, or do you mean Unity text inputs? Can you open the element inspector en see if the Unity player is blocking / overlapping your input fields?

**Comment by DamianRavi** [comment]
I have this issue too - focus does not switch to the HTML inputs.

**Comment by jeffreylanters** [comment]
Can one of you please upload an example project where this occurs? And on which browser do you test it?

**Comment by MitchEff** [comment]
Hey guys,

Turns out it was quite a common issue, but unrelated to the React component. If your Unity component doesn't require any keyboard input, adding the following to your C# scripts will sort it out:

#if !UNITY_EDITOR && UNITY_WEBGL
WebGLInput.captureAllKeyboardInput = false;
#endif

Ref: https://forum.unity.com/threads/how-to-get-rid-of-unity-canvas-collecting-all-keyboard-input.431060/

**Comment by jeffreylanters** [comment]
Thanks, @MitchEff

**Comment by damianhadji** [comment]
Hi guys,

Sorry to zombie this thread, but I had some informational that might be useful if someone comes here looking for information regarding keyboard inputs.

I was trying to figure out how to still enable keyboard inputs in my application while having this flag set:
      `WebGLInput.captureAllKeyboardInput = false;
`
After digging around in the forums, the canvas needs to be focusable. Therefore, to enable keyboard inputs we need to set the tabIndex on the Unity html canvas.

I came up with this workaround to do so, but it seemed a bit hacky. I don't know if you wanted to expose this functionality more directly @jeffreylanters ?

Here is the snippet
```javascript
const unityRef = useRef(null);
useEffect(() => {
    //Tab index required for Unity to receive keyboard inputs 
    unityRef.current.htmlCanvasElementReference.tabIndex = 1;
}, []);
return <Unity unityContext={unityContext} ref={unityRef} />;
```

**Comment by jeffreylanters** [comment]
Hi @damianhadji, sounds like a good idea, I'll look into it!

**Comment by damianhadji** [comment]
> 
> ```js
> const unityRef = useRef(null);
> useEffect(() => {
>     //Tab index required for Unity to receive keyboard inputs 
>     unityRef.current.htmlCanvasElementReference.tabIndex = 1;
> }, []);
> return <Unity unityContext={unityContext} ref={unityRef} />;
> ```

Note: This doesn't work in typescript, since htmlCanvasElementReference is private.

**Comment by jeffreylanters** [comment]
@damianhadji If you really want to, you can use the following to talk directly at the canvas element. I can add a method which exposes the tab Index?

```ts
(unityRef as any).current.htmlCanvasElementReference;
```

**Comment by damianhadji** [comment]
Thanks for the workaround. That will do for now. Maybe you could just create a public prop to (receiveKeyboardInputs : boolean = false), and just set the tabIndex in the private functions. That way it is more obvious for future users who want this functionality?
