### ISSUE TITLE
Not Receiving Callback From Quit Event In Version 8.5.1

### ISSUE THREAD

**Issue by deckercj28** [jeffreylanters/react-unity-webgl#246]
**Describe the bug**
 I recently had to update my Unity editor version, and thus with that, I had to update the React-Unity-WebGL dependency version too. I’m using Unity 2020.3.19f1 LTS version, and 8.5.1 version of React-Unity-WebGL. I noticed that the functionality for quit has changed and so I have added a callback in my code (with just a console log for now) when the Application.Quit is called, but I’m not getting a callback for some reason. I’m certain the structure is working properly as I have “loaded” and “progress” events wired up and they work perfectly. I was wondering if you can help me out with why it doesn’t seem to be calling quit for me when the game is running. Below is a sample of my code. I really appreciate if you could help me out! Thanks so much for your help!

``` 
import React, { Component } from 'react';
import './Demo.css';
import Unity, { UnityContext } from "react-unity-webgl";


class Demo extends Component {
    state = {
        displayGame: false,
        displayButton: true,
        progression: 0,
        doneLoadingGame: false
    }

    launchDemoApp(e) {
        console.log("Starting The Demo...");
        this.setState({displayButton: false})
        this.setState({displayGame: true})
    }

    render() {
        const unityContext = new UnityContext({
            loaderUrl: "Build/Demo_WebGL_Build.loader.js",
            dataUrl: "Build/Demo_WebGL_Build.data",
            frameworkUrl: "Build/Demo_WebGL_Build.framework.js",
            codeUrl: "Build/Demo_WebGL_Build.wasm",
        });

        unityContext.on("progress", progression => {
            console.log("loading progress works!");
            this.setState({
                progression: progression
            });
        });

        unityContext.on("loaded", () => {
            console.log("loaded works too!");
            this.setState({
                doneLoadingGame: true
            });
        });

        unityContext.on("loaded", function () {console.log("QUITTED APP")});
        
    return (
            <div>
                    <div className="container">
                        {this.state.displayButton &&
                        <div>
                            <div className="borderSurround">
                                <h4 className="h4Align">Welcome to the demo.</h4>
                            </div>
                            <div className="buttonAlign">
                                <button className="inputButton" onClick={() => this.launchDemoApp()}>Click To Launch Demo</button>
                            </div>
                        </div>}
                        {this.state.displayGame && !this.state.doneLoadingGame && <div className="spinner-border spinnerColor" role="status"></div>}
                        {this.state.displayGame && !this.state.doneLoadingGame && <h4>{`${Math.round(100*this.state.progression)}% Loaded`}</h4>}
                        {this.state.displayGame && 
                            <Unity 
                                unityContext={unityContext} 
                                style={{
                                height: "100%",
                                width: 950,
                                }}
                            />
                        }
                    </div>
            </div>
        );
    }
}

export default Demo

```
**To Reproduce**
When using the following code snippet below, I am not seeing a console.log back when the application quits. However, I do see internal logs stating that the application was quitted successfully.

`unityContext.on("loaded", function () {console.log("QUITTED APP")});`

**Expected behavior**
Expected the console to print out "QUITTED APP".

**Screenshots**
What the console looks with the lifespan of the WebGL run:
![image](https://user-images.githubusercontent.com/669187/137138645-66f95abf-4ac6-43ee-b8b0-29b04295b106.png)

**Details (please complete the following information):**
 - Unity Editor Version: 2020.3.19f1
 - React-Unity-WebGL Version: 8.5.1 

**Additional context**

**Comment by jeffreylanters** [comment]
Hi @deckercj28, sorry for my late response. I try to find as much time as possible to reply to issues. Did you manage to find a solution to your problem? One thing that caught my attention is an incorrect event name.

In the code you provided:
```js
unityContext.on("loaded", function () {console.log("QUITTED APP")});
                 ^^^^^^
```

In order to catch the quit event, the event name should be `quitted` instead. 

See the [documentation](https://github.com/jeffreylanters/react-unity-webgl#unmounting-unloading-and-quitting) for further details.

If this wasn't the issue, please reopen this issue so I can help your further.

Happy coding!

**Comment by deckercj28** [comment]
Thanks for taking a look at this @jeffreylanters. I may have had a simple copy paste issue there. Apologies on that! I did change the code to the following `unityContext.on("quitted", function () {console.log("QUITTED APP")});` but I am still not seeing a console log. I apologize for having the copy paste issue. Reopening for when you get a chance to look at this.
