### ISSUE TITLE
Unity URP Black Screen

### ISSUE THREAD

**Issue by JakeSchroeder** [jeffreylanters/react-unity-webgl#249]
When I build and play in browser it works but not in the react version.

1. Build using the latest of unity and this package
2. Run in react
3. Get black screen

**Expected behavior**
scene load

 - React Unity WebGL Version: 8.5.1
 - Unity Version: [e.g. 2021.2.0f1]
 - Device and OS: iMac macOS
 - Browser: Chrome
 - NodeJS Version: latest
 - Bundler: Webpack

**Comment by JakeSchroeder** [comment]
Hi Jeffrey,
I forgot to mention I am using electron to load nextjs for the client and then of course your module setup for SSR if that helps and there are no errors or stacktrace ive been able to see.

unfort adding height and width didn't fix it.

However managed to get a temp solution by:
1. Building the project using unity 2020.3.21f1 (The LTS)
2. Copying the build to my public folder (this avoids running the unity build through nextjs's webpack step)
3. Reference the build path in the unity context
4. Start the app with the <Unity/> component commented out so it runs successfully
5.  Uncomment it and refresh and boom it renders. 

Could this be related to hot module reloading or something with how electron/nextjs is mounting components? The behavior is strange but without errors its hard to give you something to trace down. 

Thanks for all your work with this module, powerful stuff.

**Comment by jeffreylanters** [comment]
Hi Jake. 

Thanks for your detailed instructions. Reading this makes me wonder; if it might be a problem with hot module reloading, does te problem occur when making a production build? Since this does not involve any hot module reloading. I'm going to look into it as well.
