### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token '<'" for 2020.2 in react-unity-webgl-tests

### ISSUE THREAD

**Issue by laffan** [jeffreylanters/react-unity-webgl#253]
**Describe the bug**
Error `Uncaught SyntaxError: Unexpected token '<'` is thrown from `myunityapp.loader.js:1` when switching react-unity-webgl-tests from the 2021.1 directory to 2021.2. 

**To Reproduce**
1. Get react-unity-webgl-tests repo, npm install.
2. Change lines 16-20 to use 2021.2 rather than 2020.1
3. `yarn start`

**Expected behavior**
For it to work the same as 2020.1.

**Details (please complete the following information):**
 - React Unity WebGL Version: 8.6.0
 - Unity Version: 2021.2
 - Device and OS: MacOS 12.0.1
 - Browser: Chrome 95.0.4638.69, Safari 15.1 
 - NodeJS Version: 14.17.0
 - Bundler: Webpack? (I think? Not sure how to verify this.)

**Additional context**
It looks as though `react-unity-webgl-tests/project` was build in 2020.1, which might be part of the problem. Unfortunately for those of us using older macs, 2020.2 fixes a horrible ViewMode framerate bug, which made development in anything _before_ 2020.2 (or after 2019.4) unworkable. 

**Update** : Rebuilding the project in 2020.2 (with compression turned off) returns the same `Uncaught SyntaxError: Unexpected token '<'` error.

**Comment by laffan** [comment]
Typo. Embarrassment.

**Comment by jeffreylanters** [comment]
Haha no worries, good luck with your project. Happy coding!
