### ISSUE TITLE
Switch to Brotli causing issue.

### ISSUE THREAD

**Issue by blakerunyon09** [jeffreylanters/react-unity-webgl#259]
**Describe the bug**
I know this is outside the confines of the package, hoping you can help though. I had the app working with gzip compression and now we're trying to move to brotli. However I'm getting this error:

<img width="1408" alt="Screen Shot 2021-11-11 at 5 06 23 PM" src="https://user-images.githubusercontent.com/65094249/141386592-74f8a13f-c715-48fc-9d07-bf1d1832cb65.png">

Here's our unityContent file:

<img width="676" alt="Screen Shot 2021-11-11 at 5 08 18 PM" src="https://user-images.githubusercontent.com/65094249/141386661-3456ee31-acc0-4410-b45c-cb04c02a1051.png">

And the build files:

<img width="528" alt="Screen Shot 2021-11-11 at 5 09 13 PM" src="https://user-images.githubusercontent.com/65094249/141386702-d7a3c89b-10dc-4055-803d-b33aacb09881.png">

And finally our server res to add br:

<img width="332" alt="Screen Shot 2021-11-11 at 5 11 13 PM" src="https://user-images.githubusercontent.com/65094249/141386856-d0e8e817-456a-46c2-89a1-815c5bf8924f.png">

**Details (please complete the following information):**
 - React Unity WebGL Version: "react-unity-webgl": "^7.1.10",
 - Unity Version: 2019.2
 - Device and OS: MacOS 12
 - Browser: Chrome/Firefox
 - NodeJS Version: 15.7.0
 - Bundler: Webpack

**Comment by blakerunyon09** [comment]
We were able to solve this issue. For posterity, we fixed this by upgrading react-unity-weggl to V8, and upgrading Unity to V20.

Thanks again for your package, it's very well maintained! :D

**Comment by binzydev** [comment]
What is Unity V20? 2020?
