### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by MichaelRazum** [jeffreylanters/react-unity-webgl#27]
Hello,

I'm trying to setup a project using react unity. I have created a build using unity and copied the files in my public folder. Using this code in App.js:

````
import React, { Component } from 'react';
import './App.css';
import Unity from 'react-unity-webgl';

class App extends Component {
  render() {
    return (
        <Unity
          src='public/buildunity/build2.json'
          loader='public/buildunity/UnityLoader.js' />
    )
  }
}
export default App;


I'm getting the error in the browser:  "(in promise) ReferenceError: UnityLoader is not defined"
Any Idea what might be wrong?
Maybe I made a mistake. The react project was created with "create-react-app". 
Thanks a lot!

**Comment by jeffreylanters** [comment]
Hi Michael. The path to your Unity files should be relative to your index and should be available to the browser. The file tree should look like this **in your case**:

```
|- index.html
|- bundle.js?
 \- public
    \- buildunity
       |- build2.json
       |- UnityLoader.js
```

**Comment by MichaelRazum** [comment]
Hi Jeffrey,

thanks a lot for your answer. I will try it out the next days! Is it correct that in that case the project should be build first to run it? Right now I'm starting it with 'react-scripts start'.

**Comment by jeffreylanters** [comment]
Once your project is Build is should work.

**Comment by MichaelRazum** [comment]
That worked. Actually, I'm not that experienced with javascript / webpack. It was a webpack Issue. A simple workaround was for me to place the files directly in the public folder.

**Comment by jeffreylanters** [comment]
No problem. A little bit of background information; the reason I don’t add your Unity code into the JavaScript bundle is due to it’s size. I would make your application very slow and big in file size. Plus Unity loads additional blobs in run-time, so it needs direct access to the other build files. 

If you have any other questions feel free to reopen your issue.

**Comment by smilexu** [comment]
I did not find src & loader props from the component Unity, but it looks like some nice way to dynamic load unity resources instead of package everything into js bundle. Could you give the relative document ?

**Comment by Mounajidev** [comment]
Hello, i did make it work over and my WebGL app works fine on the react app in localhost, but after i run npm run build, it brokes and i get the error " couldnt find the Loader",  and also if i try to publish on gh pages, or fleek, i got the same error. but before building it was working good. Anything i can do to make it works properly on a published page ? thanks !

**Comment by jeffreylanters** [comment]
@Mounajidev your directory starts with an uppercase letter, your configuration doesn't.

**Comment by Mounajidev** [comment]
> @Mounajidev your directory starts with an uppercase letter, your configuration doesn't.

thanks for your reply @jeffreylanters,  i tried it by different ways, but it are not working now even if i use same capitals letters.

![image](https://user-images.githubusercontent.com/75537911/148786895-2ce9f929-e6e2-4fc4-9b24-842865985aff.png)
