### ISSUE TITLE
All useState hooks block work of setFullScreen.

### ISSUE THREAD

**Issue by sanscrid6** [jeffreylanters/react-unity-webgl#284]
I added useState hook to my project and setFullScreen function stopped work. It just dont wont to set full screen.

I added this and fullscreen crushed

  _useEffect(function () {
    unityContext.on("progress", function (progression) {
      console.log(progression);
      setProgress(progression);
    }
    );
  }, []);_

**Comment by jeffreylanters** [comment]
You're probably recreating the UnityContext object somewhere. Could you try creating the UnityContext inside of a UseEffect hook as an ComponentDidMount effect, or outside of the competent at all? Let me know if this helps.

**Comment by sanscrid6** [comment]
I just use browser fullscreen api instead of unity context setFullscreen function and it works.

**Comment by jeffreylanters** [comment]
Could you provide an example of what you did? Thanks
