### ISSUE TITLE
Canvas event is not triggered

### ISSUE THREAD

**Issue by romy-piche** [jeffreylanters/react-unity-webgl#300]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Other TypeScript compiler

### What environment are you using?

Local Development Server

### When does your problem occur?

While the Unity App is loading

### What does your problem relate to?

I don't know

### React-Unity-WebGL Version

latest

### React Version

latest

### Unity Version

2021.2

### What happened?

The canvas event is not triggered in the latest version(v8.7.2).

Using the test environment with the latest version, the canvas event is not triggered (**_handleOnUnityCanvas function_**) : https://github.com/jeffreylanters/react-unity-webgl-tests

However, the event is triggered in versions prior to v8.6.0 (ex v8.5.2).

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
Hi Romy. Thanks for opening this issue, I will take a look at this problem. I'll keep you posted here!

**Comment by jeffreylanters** [comment]
It seems to be a timing issue. In the module, the event is triggered when the canvas is mounted. But this life cycle is triggered before, in the test application, the on("canvas",... event listener is registered. I'm looking into a solution.

**Comment by romy-piche** [comment]
Thanks !

**Comment by jeffreylanters** [comment]
I've came up with a fix, I'll test it and will publish it today!

**Comment by romy-piche** [comment]
Thank you for the quick response !

**Comment by jeffreylanters** [comment]
Hi! I've released version [8.7.3](https://github.com/jeffreylanters/react-unity-webgl/releases/tag/v8.7.3), this should fix your issue! Please let me know if this resoles the problem.

**Comment by romy-piche** [comment]
Just tested it, and I confirm you that it solved the issue. Thank you !

**Comment by jeffreylanters** [comment]
Great! Happy coding and best of luck with your project!
