### ISSUE TITLE
WebGL Canvas Size Grows Indefinitely

### ISSUE THREAD

**Issue by RazrSlyr** [jeffreylanters/react-unity-webgl#301]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Vanilla JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

When the Unity App starts

### What does your problem relate to?

I don't know

### React-Unity-WebGL Version

8.7.2

### React Version

17.0.2

### Unity Version

2020.3.23f1

### What happened?

The moment the unity app loads it begins to expand in size seemingly till no end. Here is a recording of the phenomenon: https://drive.google.com/file/d/1lidgq8rA_tT_ZqzoIijmJDJ9spYMAOoG/view?usp=sharing. Manually setting the webgl canvas size seems to fix the issue but it also makes the game blurry, so I was wondering if there was any other way around this issue. This seems to happen on all browsers but interestingly enough it seems to impacted by resolution. This occurs on 1920x1080p and above for me but when running the web page in 720p everything goes as expected.

### Reproducible test case

import logo from './logo.svg';
import './App.css';
import {useEffect} from "react";
import Unity, {UnityContext} from "react-unity-webgl";

function App() {

    const unityContext = new UnityContext({
        loaderUrl: "build/Web.loader.js",
        dataUrl: "build/Web.data",
        frameworkUrl: "build/Web.framework.js",
        codeUrl: "build/Web.wasm",
    });

    return (
        <div>
            <Unity
                unityContext={unityContext}
            />
        </div>
    );
}

export default App;

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
Hi. This is a know issue what later Unity version. If you provide a height and width to the canvas using either styles or a classname, this should be solved. Let me know if this helps.

**Comment by jeffreylanters** [comment]
Edit: To make your game less blurry, you can set the device pixel ratio.
