### ISSUE TITLE
UnityContent.send Uncaught abort(176) Error #305

### ISSUE THREAD

**Issue by thesoulkiller** [jeffreylanters/react-unity-webgl#308]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Vanilla JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

When the Unity App is running

### What does your problem relate to?

The problem seems Module related

### React-Unity-WebGL Version

7.1.13

### React Version

17.0.2

### Unity Version

2019.4.33f1

### What happened?

Hello !

First of all thank you for working on this kind of library, it's really helpful. 
I'd like to point out an issue that I'm facing. I can perfectly catch the events thrown from Unity in React however I can't call a Unity function from React side. It gives error: 
```
Uncaught abort(176) at Error\n    at jsStackTrace (…ttp://localhost:3000/static/js/bundle.js:133
```

I'm using the codes from documentation [here](https://www.npmjs.com/package/react-unity-webgl/v/7.1.13)
The React side:
```javascript

export class App extends React.Component {
  constructor(props) {
    super(props);

    this.unityContent = new UnityContent(
      "game/WebBuild.json",
      "game/UnityLoader.js"
    );

    this.unityContent.on("GameOver", (score) => {
      console.log("score: ", score);
    });
  }

  onClick() {
    this.unityContent.send("WebCalls", "aaa", 10);
  }

  render() {
    return (
      <div>
        <button onClick={this.onClick.bind(this)}>Spawn!</button>
        <br />
        <Unity
          unityContent={this.unityContent}
        />
      </div>
    );
  }
}
```

The Unity 3d side:
```csharp
public void aaa(int ID)
    {
        Text.text = "ID : " + ID;
    }
```

```csharp
using TMPro;
using UnityEngine;

public class BackendCalls : MonoBehaviour
{
    public TextMeshProUGUI Text;

    public void aaa(int ID)
    {
        Text.text = "ID : " + ID;
    }
}
```

I've tried the below codes and I successfully can receive the score in the React side. But not the reverse of that.
```
GameOver: function (score) {
    ReactUnityWebGL.GameOver(score);
  },
```
```csharp
[DllImport("__Internal")]
    private static extern void GameOver(int score);

    void Start()
    {
        GameOver(50);
    }
```

Versions:
Unity 2019.4.33f1
react-unity-webgl: "7.1.13"

Any help is appreciated
Thank you !

### Would you be interested in contributing a fix?

- [X] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
Hi! Thanks for your issue. Just double checking, can you confirm the script "BackendCalls" is attached to a game object in your active scene?

**Comment by thesoulkiller** [comment]
Yes I've double checked it now.

**Comment by thesoulkiller** [comment]
Hello @jeffreylanters , sorry it was a problem about my build.
