### ISSUE TITLE
Sending event form React to Unity changes int parameter value

### ISSUE THREAD

**Issue by mikirov** [jeffreylanters/react-unity-webgl#329]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

TypeScript's built-in Compiler

### What environment are you using?

Local Development Server

### When does your problem occur?

When the Unity App is running

### What does your problem relate to?

The problem seems Module related

### React-Unity-WebGL Version

8.6.0

### React Version

17.0.2

### Unity Version

2021.2.7f1

### What happened?

When i try to send an event from react to unity and pass an integer parameter, the parameter is changed when received on the unity side.

### Reproducible test case

//React side  
const GeneratePlanet = (seed: string) => {
                if(!seed)
                {
                    console.log("No seed supplied for planet generation");
                    return;
                }
                console.log(seed)
                const seedNumber = parseInt(seed);
                console.log(seedNumber);
                unityContext.send("GameController", "GeneratePlanet", seedNumber);
            }

//unity side
    public void GeneratePlanet(int seed)
    {
        Debug.Log(seed); ;
        NFTController.Instance.GeneratePlanet(seed);
        Player.transform.position = new Vector3(0, NFTController.Instance.GetMaxPoint(), 0);
        OrbitingCamera.position = new Vector3(0, 0, -NFTController.Instance.GetMaxPoint() - 200);
    }
<img width="544" alt="Screenshot 2022-02-20 at 15 18 54" src="https://user-images.githubusercontent.com/29272392/154845065-20fe17ae-12f6-4782-873a-e56db0fd7f4e.png">

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
Hi! Sorry, I've missed your question. 

Unity only supports receiving string messages. This is a limitation on their side, so in order to resolve this problem, a parse is needed somewhere in your c-sharp code.

However my module allows sending int values to prevent the need to do an extra cast. 

I hope this helped you! Happy coding!
