### ISSUE TITLE
Accessing unityInstance from HTML templates

### ISSUE THREAD

**Issue by OlafSzmidt** [jeffreylanters/react-unity-webgl#38]
Hi all,

I'm pretty new to Unity and WebGL so it would be appreciated if anyone here could help. I'm interested in using `react-unity-webgl` in my React project, which is then embedded into a django template. The django template in my previous version would have a variable within script tags that contains the `UnityLoader.instantiate` call. That variable would be then used in our socket wrapper in Unity.

Now, the problem is this is done all internally within this package. The snippet of code I'm interested here is:

https://github.com/jeffreylanters/react-unity-webgl/blob/master/source/components/Unity.js#L31
```javascript
      this._unityLoaderService.append(this.props.loader).then(() => {
        let unityInstance = UnityLoader.instantiate("__ruw", this.props.src, {
          onProgress: this._onProgress.bind(this),
          Module: this.props.module
        });
        module.exports.UnityInstance = unityInstance;
      });
```

Is there any way to access `unityInstance` within the HTML tags cleanly? Or do I have to resort to some hacky alternatives like requiring the module explicitly? :)

**Comment by OlafSzmidt** [comment]
I managed to solve this by simply calling `SendMessage()` in the Django template (not exactly sure how I got access to it), but it would still be nice to know if `unityInstance` is accessible?

**Comment by jeffreylanters** [comment]
No, the `UnityInstance` is not exposed in the current verison. However I'm reworking the whole plugin in `7.0.0` which will expose the `UnityInstance`. But it's still in progress.
