### ISSUE TITLE
Cannot have multiple canvas's

### ISSUE THREAD

**Issue by zinroc** [jeffreylanters/react-unity-webgl#4]
` {arr.map(item => (
              <div key={item.key}>
                        <Unity  src="/unity/Builds.json" />
              </div>))}`

Only the first div will get a canvas (arr[0]) the other ones will have .unity, .unity-container, but no canvas.

**Comment by jeffreylanters** [comment]
Thanks for your issue. This is true, it is because the Unity canvas wil be binded to an single instance. I will look into to!

**Comment by jeffreylanters** [comment]
This issue has been scheduled for the next release `7.0.0`.

**Comment by jeffreylanters** [comment]
I'm happy to announce that [7.0.0](https://github.com/jeffreylanters/react-unity-webgl/releases/tag/7.0.0) has finally released. Please see the [documentation](https://github.com/jeffreylanters/react-unity-webgl/wiki) for further instructions on how to implement the new library. Multiply canvases are now available!
