### ISSUE TITLE
Returning values from bound React functions

### ISSUE THREAD

**Issue by alzab** [jeffreylanters/react-unity-webgl#40]
In /library/modules/RegisterExternalListener it appears that 'callback' is called but its return value is not returned (i.e. on line 26). Is this a deliberate design decision?

Without this, it doesn't seem to be possible to directly get the return value of a React function from a jslib (Unity) call. Or is there a preferred way to 'pull' data that I'm missing?

**Comment by jeffreylanters** [comment]
No, It's should return your value. Which version of Unity are you using? Can you post some example code. And feel free to create a pull request if you've found a solution.

**Comment by alzab** [comment]
Unity version 2018.1.3f1 - not sure this is a Unity issue though. I managed to tentatively fix it by changing `callback(parameter);` to `return callback(parameter);` on line 26 of /library/modules/RegisterExternalListener.js.

To summarise the issue with a code example:

In React component `constructor()`:
`RegisterExternalListener("MyFunc", this.myFunc.bind(this));`
...
`myFunc() {
    return 4;
}`

Jslib:
```
mergeInto(LibraryManager.library, {
  MyFunc: function() {
    return ReactUnityWebGL.MyFunc();
  }
});
```

ReactUnityWebGL.MyFunc() will return 'undefined' (i.e. not '4' as it should in this instance), thus the value returned by the bound Unity function will just be a default of '0'.

**Comment by jeffreylanters** [comment]
Are you sure it's not working? I can't follow you. The following code should work, you can test it on your console.

```js
// This is the code from my Library as it is now
// https://github.com/alzab/react-unity-webgl/blob/3db8295c9a9ae1c755a3179590dacdcdfa8db08d/source/modules/RegisterExternalListener.js#L18
function RegisterExternalListener(methodName, callback) {
  if (typeof window.ReactUnityWebGL === 'undefined')
    window.ReactUnityWebGL = {}
  window.ReactUnityWebGL[methodName] = parameter => {
    callback(parameter)
  }
}

// Registering an external listener
RegisterExternalListener("test1", parameter => { 
  console.log(parameter); 
});

// Triggering the code by hand 
window.ReactUnityWebGL.test1("I am a value, I should work without return!");
```

**Comment by alzab** [comment]
Sorry I must not be explaining myself clearly. The issue isn't that the function isn't called without return being there, it's that the actual return value isn't returned. I'll modify your example to demonstrate:

```
function RegisterExternalListener(methodName, callback) {
  if (typeof window.ReactUnityWebGL === 'undefined')
    window.ReactUnityWebGL = {}
  window.ReactUnityWebGL[methodName] = parameter => {
    callback(parameter)
  }
}

// Registering an external listener
RegisterExternalListener("test1", parameter => { 
  return 4;
});

// Triggering the code by hand 
console.log(window.ReactUnityWebGL.test1());
```

This should output '4', but the implementation above outputs 'undefined'. For this to work, `callback(parameter)` needs to be changed to `return callback(parameter)`. Unless I'm missing something about how the library is meant to be used?

**Comment by jeffreylanters** [comment]
Thanks for you contribution! Your changes have been publish to NPM with version [5.6.1](https://github.com/jeffreylanters/react-unity-webgl/releases/tag/6.5.1).
