### ISSUE TITLE
ReactUnityWebGL is not defined

### ISSUE THREAD

**Issue by sunlili810** [jeffreylanters/react-unity-webgl#429]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Vanilla JavaScript

### What environment are you using?

Static File Serving

### When does your problem occur?

While writing code

### What does your problem relate to?

The problem seems Unity related

### React-Unity-WebGL Version

9.0.4

### React Version

17.0.0

### Unity Version

2020.3

### What happened?

mergeInto(LibraryManager.library, {
  HelloFn: function (userName, score) {
    ReactUnityWebGL.HelloFn(Pointer_stringify(userName), score);
  },
});

### Would you be interested in contributing a fix?

- [X] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
The ReactUnityWebGL object is only available in version 8. This is replaced with the dispatchReactUnityEvent method in version 9.

Read more: https://react-unity-webgl.dev/docs/api/event-system

**Comment by jeffreylanters** [comment]
```js
mergeInto(LibraryManager.library, {
  SetScore: function (score) {
    try {
      window.dispatchReactUnityEvent("SetScore", score);
    } catch (e) {
      console.warn("Failed to dispatch event");
    }
  },
});
```

**Comment by sunlili810** [comment]
> ```js
> mergeInto(LibraryManager.library, {
>   SetScore: function (score) {
>     try {
>       window.dispatchReactUnityEvent("SetScore", score);
>     } catch (e) {
>       console.warn("Failed to dispatch event");
>     }
>   },
> });
> ```

Thanks a lot!

**Comment by jeffreylanters** [comment]
Awesome! Happy coding.
