### ISSUE TITLE
Version 7.x testers needed!

### ISSUE THREAD

**Issue by jeffreylanters** [jeffreylanters/react-unity-webgl#43]
I'm happy to announce version 7 of my library finally released! I've put a lot of work into this library so if you've found any errors feel free to edit the [documentation](https://github.com/jeffreylanters/react-unity-webgl/wiki) or create a pull request. To learn more about contributing please look at the contribution page on this wiki. Have a great day!

**Comment by ray-su** [comment]
Just upgraded from v6 to v7.  
the "Calling Unity methods from React" and the "Communication from React to Unity"  page in the WIki confused me a bit. 

One suggested using `this.unityContent.send,`   and the other suggested using `this.unityContent.sendMessage.`   

I tested with both  `this.unityContent.send,`  is the one that works. 

When I use `this.unityContent.sendMessage.`   it will get into errors saying `this.unityContent.sendMessage.`    is not a function.

**Comment by jeffreylanters** [comment]
Thanks for noticing! It should have been `send` instead of `sendMessage`. I've updated the docs, thanks! @ray-su

**Comment by alanionita** [comment]
@jeffreylanters  Happy to chip in too! We use the library a lot an would love to help out where possible. Planning to start testing next week. 

Thanks for the work you're putting in! 🙌

**Comment by jeffreylanters** [comment]
@alanionita that's great to hear! Thank you so much. I'd love to hear your feedback and experience. If you're missing any features or see improvements feel free to contribute. Have a great weekend!
