### ISSUE TITLE
Unity, useUnityContext not found in 'react-unity-webgl'

### ISSUE THREAD

**Issue by nwoodr94** [jeffreylanters/react-unity-webgl#461]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Babel and WebPack JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

While writing code

### What does your problem relate to?

The problem seems React related

### React-Unity-WebGL Version

8.8.0

### React Version

18.1.0

### Unity Version

2021.3.5f1

### What happened?

`import { Unity, useUnityContext } from "react-unity-webgl";`

Produces the following error:

`export 'useUnityContext' (imported as 'useUnityContext') was not found in 'react-unity-webgl' (possible exports: UnityContext, __esModule, default)`

### Reproducible test case

Copy and paste the example code (from https://react-unity-webgl.dev/docs/getting-started/hello-world)

The code does not compile.

```
import React from "react";
import { Unity, useUnityContext } from "react-unity-webgl";
function App() {
  const { unityProvider } = useUnityContext({
    loaderUrl: "path/to/my/loader.js",
    dataUrl: "path/to/my/build.data",
    frameworkUrl: "path/to/my/build.framework",
    codeUrl: "path/to/my/build.wasm",
  });
  return <Unity unityProvider={unityProvider} />;
}
```

![image](https://user-images.githubusercontent.com/46133948/199123592-918c9286-ecac-47e5-855a-85be0263283a.png)

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
Hi. Would it be possible for you to share your Webpack configuration?

**Comment by nwoodr94** [comment]
Hi, I took a look at a coworker's `package.json` and noticed that he has an updated version.

I was on 8.8.0, but after upgrading to 9.0.4, this issue went away. 

I'm using `react-scripts` through `create-react-app`, so I don't have immediate access to the Webpack.

**Comment by jeffreylanters** [comment]
Ah perfect! Thanks for letting me know. Happy coding!
