### ISSUE TITLE
AudioContext

### ISSUE THREAD

**Issue by sampuls1** [jeffreylanters/react-unity-webgl#462]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Babel and WebPack JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

When the Context is created

### What does your problem relate to?

The problem seems Browser related

### React-Unity-WebGL Version

9.2.1

### React Version

18.2.0

### Unity Version

2021.3.11f1

### What happened?

Is anyone facing this issue? Unity 2021.3.11f1, with v 9.2.1

The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. <URL>

### Would you be interested in contributing a fix?

- [X] yes, I would like to contribute a fix

**Comment by sampuls1** [comment]
I used "Disable unity audio" in project settings and that resolved the above issue

**Comment by jeffreylanters** [comment]
Perfect! Thanks for updating me.
