### ISSUE TITLE
React router

### ISSUE THREAD

**Issue by lolik20** [jeffreylanters/react-unity-webgl#463]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Other JavaScript compiler

### What environment are you using?

Local Development Server

### When does your problem occur?

I don't know

### What does your problem relate to?

The problem seems Module related

### React-Unity-WebGL Version

last

### React Version

15

### Unity Version

last

### What happened?

I have react router and i want add webgl game on page

### Reproducible test case

import style from "./game.module.css" 
import React from "react";
import loaderUrl from "./Build/build.loader.js"
import dataUrl from "./Build/build.data.br"
import frameworkUrl from "./Build/build.framework.js.br"
import codeUrl from "./Build/build.wasm.br"
import { Unity, useUnityContext } from "react-unity-webgl";

export default function Game (){

      const { unityProvider } = useUnityContext({
    loaderUrl: loaderUrl,
    dataUrl:dataUrl,
    frameworkUrl: frameworkUrl,
    codeUrl: codeUrl
  });

    return(
        < div className={style.container}>
             < Unity unityProvider={unityProvider} />
        < /div>
    );

}
![image](https://user-images.githubusercontent.com/58035814/200358502-cb9fe6e1-0be9-446e-9bf9-dbac4121fe84.png)
![image](https://user-images.githubusercontent.com/58035814/200358588-51005c5f-28b0-412e-845a-085270232a17.png)
![image](https://user-images.githubusercontent.com/58035814/200359058-3cc07d3f-f7ff-43a7-8790-1f7f8a1c7471.png)

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by vokhuyetOz** [comment]
you should put your Build in public folder.
