### ISSUE TITLE
Does this library work with React Native?

### ISSUE THREAD

**Issue by Eyesonly88** [jeffreylanters/react-unity-webgl#48]
**Is your feature request related to a problem? Please describe.**
Does this library work with React Native?

**Additional context**
I was researching embedding a Unity scene in a react native app and found this library. So I'm wondering if it's possible to use this library in a React Native app?

**Comment by jeffreylanters** [comment]
No, this library is made for WebGL using ReactJS.

**Comment by Eyesonly88** [comment]
Ok I see, thanks. I was thinking of hooking it up with `react-native-webgl` and see how it goes. Unless someone has already tried this approach?

**Comment by jeffreylanters** [comment]
I don't think it's possible with Unity. It requires a custom integration. `react-native-webgl` only works for WebGL 1.0 and Unity uses 2.0. But you can always try or go web ReactJS and use a `WebKitWebView` in your React Native app. `react-unity-webgl` works on mobile as well.

**Comment by Eyesonly88** [comment]
@jeffreylanters thank you so much for your notes. I wasn't sure which version Unity used for webgl. Good point regarding embedding a `WebkitWebView`. I tried before with a `WebView` in the React Native side, but was choppy. However, I think using `WebkitWebView` as you suggested and just do it in the native side might lead to better results!
Thanks!

**Comment by jeffreylanters** [comment]
Thank you too! If you'd like, like me know if you manage to get it working using React Native. :)
