### ISSUE TITLE
Warning: Prop `id` did not match ERROR, unable load WEBGL Unity Game

### ISSUE THREAD

**Issue by xavieracaling** [jeffreylanters/react-unity-webgl#481]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Vanilla JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

While writing code

### What does your problem relate to?

The problem seems React related

### React-Unity-WebGL Version

latest

### React Version

latest

### Unity Version

latest

### What happened?

![errorr1](https://user-images.githubusercontent.com/97587477/213884618-c7db055e-0339-4e53-b35f-2a176c2f6925.jpg)
![error2](https://user-images.githubusercontent.com/97587477/213884621-eef015ee-ceb1-4408-b24f-0ca9dedef3ca.jpg)

This is the error and my code.
What seems to be the problem? I can't LOAD my WEBGL GAME ,I've followed the instructions though.

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
#482
