### ISSUE TITLE
Can't correctly invoke a function with a string parameter on React by Unity

### ISSUE THREAD

**Issue by Muntaner** [jeffreylanters/react-unity-webgl#49]
**Describe the bug**
In a sample project, I'm invoking a function within the Unity WebGL application to the React component, with a string as a parameter. This string is a simple sentence, but becomes an integer (which changes with time) when I get it in the React component listener. May this be some strange pointer issue?

**To Reproduce**
1. Unity snippets:
```
void Update () {
    if (Input.GetMouseButtonDown(1))
      this.OutgoingMsgR("THIS IS FOR REACT!");
  }

  [DllImport("__Internal")]
  private static extern void OutgoingMsg(string message);
  public void OutgoingMsgR (string message) {
    Debug.Log(message);
      OutgoingMsg(message);
  }

```
JSLib plugin:

```
mergeInto(LibraryManager.library, {
  OutgoingMsg: function(message) {
    ReactUnityWebGL.OutgoingMsg(message);
  }
});

```
2. React snippets: 
```

this.unityContent.on("OutgoingMsg", message => {
      console.log(message)
      this.setState({
        ...
      })
    })
```

Here, the _message_ variable should be _THIS IS FOR REACT!_ , but I'm getting these integers instead (just some samples, the integer seems to be growing with time):

- 17884352
- 17905344 
- 17942320
- 17942320
- 17976784
...

Expected behavior
I should receive the string I'm sending from Unity into the React component.

Screenshots
N. d.

Desktop (please complete the following information):
 - OS: Fedora 28
 - Chrome, latest

Smartphone (please complete the following information):
Not tested.

Additional context
Nothing particular. Function invocation works flawlessly with integer variables.

**Comment by Muntaner** [comment]
I found myself the solution. I'm very sorry: this isn't a **react-unity-webgl** issue, but it is related to JSLib plugins.

To correctly use a string as a parameter, in the JSLib plugin, you should do the following:

```
mergeInto(LibraryManager.library, {
  OutgoingMsg: function(message) {
    ReactUnityWebGL.OutgoingMsg(Pointer_stringify(message));
  }
});
```

As also reported in the [official Unity documentation](https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html).

**Comment by SherikarRohith** [comment]
React Unity WebGL ErrorEvent {isTrusted: true, message: "Script error.", filename: "", lineno: 0, colno: 0, …}


Uncaught SyntaxError: Unexpected token / in JSON at position 0
    at Object.parse (<anonymous>)
    at XMLHttpRequest.t.onload (UnityLoader.js:4)

getting these two errors if i change the JSLib file as you mentioned above
