### ISSUE TITLE
Can't load UnityLoader

### ISSUE THREAD

**Issue by AidinD** [jeffreylanters/react-unity-webgl#5]
I have a create-react-app project and try to embed a Unity game built to WebGl.

I have installed and updated your package to v.6.0.0

And then my complete code in the component where I try to embed the game:

    import React from 'react';
    import classnames from 'classnames';
    import './Games.css';
    import '../../assets/styles/Animations.css';

    import Unity from 'react-unity-webgl';

    export default class Games extends React.Component {
      render() {
        const { className } = this.props;

        return (
          <div className={classnames('Games', className)}>

            <section className="spaceshooter">
              <Unity
                src='../../assets/games/SpaceShooter/Build/SpaceShooter.json'
                loader='../../assets/games/SpaceShooter/Build/UnityLoader.js'
              />
            </section>
          </div>
        );
      }
    }

This gives me the console error: 

```
Uncaught SyntaxError: Unexpected token <         UnityLoader.js:1

G:\Repo\React\aidin.se\node_modules\react-unity-webgl\lib\Unity.js:62 Uncaught (in promise) ReferenceError: UnityLoader is not defined
    at G:\Repo\React\aidin.se\node_modules\react-unity-webgl\lib\Unity.js:62
    at <anonymous>
```

I am positive that the path is correct. 
When looking in the Network tab of Chrome development tools, it seems that what was returned in UnityLoader.js is the index.html from the public folder.

**Comment by jeffreylanters** [comment]
Hi! Can you please upgrade to the latest version, the UnityLoader will be embedded by the component itself. Make sure you use the correct path, check your resources in the browsers inspector to see if the asset is loaded successfully.

**Comment by jeffreylanters** [comment]
`<Unity 
            src='Build/myGame.json' 
            loader='Build/UnityLoader.js' />`

**Comment by AidinD** [comment]
I finally got it to work. But I am not sure this is the expected behaviour? Where is the path `Build/UnityLoader.js` pointing? The only way I got it to work was if I put my game in the public folder since the path seems to use public as root. 

Is it really in the public folder I should put my games?

**Comment by jeffreylanters** [comment]
I see the misunderstanding, the Unity component loads your content in runtime, not compile time. Your Unity build has to be in your public folder.

**Comment by meabhilashtiwari** [comment]
Hi, I am building a custom react package and trying to use react-unity-webgl library, but unity static files are not loading can you please help check my code below - 

Component

`import React from 'react';
import { Unity, useUnityContext } from "react-unity-webgl";

const DigitalTwinUnityLoader: React.FC = () => {   
    const { unityProvider } = useUnityContext(
        {
            loaderUrl: "/unity/Build/WebGLExport.loader.js",
            dataUrl: "/unity/Build/WebGLExport.data",
            frameworkUrl: "/unity/Build/WebGLExport.framework.js",
            codeUrl: "/unity/Build/WebGLExport.wasm",
        }
    )
    return (
        <div style={{ width: '100%', height: '100%', }}>
            <Unity unityProvider={unityProvider}  />
        </div>
    )
}

export default DigitalTwinUnityLoader;`

webpack config
`const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
    entry : './src/index.tsx',
    output:{
        publicPath: '/public/',
        path:path.resolve(__dirname,'dist'),
        filename:'index.js',
        library:'ditpackage',
        libraryTarget:'umd',
        globalObject:'this'
    },
    module:{
        rules:[
            {
                test:/\.(ts|tsx)$/,
                exclude:/node_modules/,
                use:'ts-loader'
            },
            // {
            //     test:/\.wasm$/,
            //     type:'asset/resource'
            // },
            // {
            //     test:/\.(data|loader|framework)$/,
            //     type:'asset/resource'
            // },           
            // {
            //     test: /\.(js|data|wasm)$/,
            //     loader: 'file-loader',
            //     // type:'asset/resource',
            //     options: {
            //         name: '[path][name].[ext]'
            //     }
            // },  
        ]
    },
    resolve:{
        extensions:['.ts','.tsx','.js','.jsx']
    },
    mode:'production',
    experiments:{
        asyncWebAssembly :true
    },
    externals:{
        react:'react',
        'react-dom':'react-dom'
    },
    // plugins:[
    //     new CopyWebpackPlugin({
    //         patterns:[
    //             {from:'public/', to:'public/'}
    //         ]
    //     })
    // ],
 
}`
