### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by juankxxD** [jeffreylanters/react-unity-webgl#529]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Babel and WebPack JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

When the Unity Component mounts

### What does your problem relate to?

The problem seems Unity related

### React-Unity-WebGL Version

9.4.3

### React Version

18.2.0

### Unity Version

2022.3.11f1

### What happened?

When I create the useUnityContext and place the Unity component, these errors appear:

Uncaught SyntaxError: Unexpected token '<' (at build.framework.js:1:1)

Unable to parse Build/build.framework.js! The file is corrupt, or compression was misconfigured? (check Content-Encoding HTTP Response Header on the web server)
build.loader.js:1 Uncaught ReferenceError: unityFramework is not defined

at i.onload (build.loader.js:1:7809)
And then, this message appears:

[UnityCache] 'http://localhost:3000/Build/build.data' successfully downloaded and stored in the indexedDB cache

### Reproducible test case

![image](https://github.com/jeffreylanters/react-unity-webgl/assets/43628180/d20d8090-b702-460e-82e4-4c2b4e1158bd)
![image](https://github.com/jeffreylanters/react-unity-webgl/assets/43628180/dd6b1be3-47bd-4098-90a6-4d6d937987e9)

### Would you be interested in contributing a fix?

- [X] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
Could you try removing the leading period from the URLs?

**Comment by juankxxD** [comment]
I already fixed it, the problem was with the extension of my build files, I had to use the 'gunzip' command on each '.gz' file to decompress 'build.framework.js.gz', and it's working now.
