### ISSUE TITLE
unityContext is undefined, Uncaught TypeError: Cannot read properties of undefined (reading 'unityConfig')

### ISSUE THREAD

**Issue by zetachua** [jeffreylanters/react-unity-webgl#538]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Vanilla JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

While writing code

### What does your problem relate to?

The problem seems Module related

### React-Unity-WebGL Version

9.5.0

### React Version

18.2.0

### Unity Version

2022.3.16f1

### What happened?

I literally just pasted the getting started code and created a react project, my file structure is 

react-unity-webgl
--core
--web
----public
------Build2
----src
------app.jsx

its saying that unityContext is undefined... i have no idea what to do as ive looked thru all the forms and chatgpt...send help thanks

### Reproducible test case

import './App.css'
import { Unity, useUnityContext} from "react-unity-webgl";

function App() {
    const {unityContext} = useUnityContext({
      loaderUrl: "/Build2/Build2.loader.js",
      dataUrl:"/Build2/Build2.data.unityweb",
      frameworkUrl:"/Build2/Build2.framework.js.unityweb",
      codeUrl: "/Build2/Build2.wasm.unityweb",
    });
    console.log(unityContext,"meow")
    return <Unity unityProvider={unityContext} />
    ;
  }

export default App;

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
You need to deconstruct `unityProvider` from the `useUnityContext` hook, you're trying to deconstruct `unityContext` instead - which is indeed not defined.

**Comment by zetachua** [comment]
Hey Jeffrey! I just tried that it works! thank you:)
