### ISSUE TITLE
Make compatible with `--isolatedModules` TypeScript flag

### ISSUE THREAD

**Issue by rivertam** [jeffreylanters/react-unity-webgl#54]
**Describe the bug**

When doing nothing but `import`ing the project as such:

```ts
import Unity, { UnityContent } from 'react-unity-webgl';
```

TypeScript with the `isolatedModules` flag gives the error:

```
Type error: Cannot re-export a type when the '--isolatedModules' flag is pr
ovided.  TS1205

    4 | import { UnityVersion } from "./enums/UnityVersion";
    5 |
  > 6 | export { IUnityConfig, UnityContent, UnityVersion };
      |          ^
    7 | export default Unity;
    8 |
```

**To Reproduce**
I can make detailed reproduction steps, but I don't think it's necessary in this instance.

**Expected behavior**
I expect at least for it to build. =)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: N/A (Node @ 10.2.1, TypeScript @ 3.2.2)
 - Version: 7.07 on npm

**Additional context**
Hello! I know this is not truly a bug, but Create React App with the default TypeScript options actually does not seem to allow you to turn this flag off, so this module is unusable in CRA with TypeScript. It's not that big of a deal, but I suspect it's a quick fix. I will look into fixing it myself.

**Comment by rivertam** [comment]
I tried to fix this, but more issues popped up. It seems much of this library is non-compatible with Babel 7's built in TypeScript transpiler. I no longer know if it's a good idea to make it compatible. For now, I'm going to do without the TypeScript portions, but this may very well be a common problem going forward for users of CRA.

**Comment by jeffreylanters** [comment]
Thanks for your report @rivertam! I've looked into it, and there was no need to export the interface anyway. I removed it from the index exporter. Could you try if this fixes your issue? See release version [7.0.8](https://github.com/elraccoone/react-unity-webgl/releases/tag/7.0.8).

**Comment by rivertam** [comment]
Hey @jeffreylanters, I really appreciate your time on this. Unfortunately, there's still an issue:

```
Type error: Cannot compile namespaces when the '--isolatedModules' flag is provided.  TS1208

  > 1 | declare class UnityLoader {
      | ^
    2 |   constructor();
    3 |
    4 |   /**
````

I've created a minimal viable reproduction so you can test for yourself if you'd like to:

https://github.com/rivertam/react-unity-webgl-issue-mvr

**Comment by jeffreylanters** [comment]
Hey @rivertam. Thanks for the mvr! I will look into this, I have to say I don't really know what the use is of the isolated modules compiler options. I [see](https://www.typescriptlang.org/docs/handbook/compiler-options.html) this is turned off by default when using the official Typescript compiler. I'll keep you up-dated! If you manage to find a fix for this issue before I do, feel free to create a pull request.

**Comment by rivertam** [comment]
@jeffreylanters Yep, I can't answer that either. I just know that the TS compiler that comes with babel 7 doesn't support the option being off, or at least that's what I hear when trying to figure out why Create React App's built in TypeScript has the option on.

**Comment by jeffreylanters** [comment]
Is Created React App for TypeScript packages with Babel loaders? Odd, why would you need Babel if you’re using TypeScript. I just plug the TypeScript loader directly into my WebPack config. I’ll look into it.

**Comment by rivertam** [comment]
@jeffreylanters Babel 7 I believe natively supports TS. This is better explained I think by the relevant issues.

https://github.com/facebook/create-react-app/issues/4146 here's one
