### ISSUE TITLE
Full Screen event is not working on I Phone

### ISSUE THREAD

**Issue by jahansoft** [jeffreylanters/react-unity-webgl#558]
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Vanilla JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

While writing code

### What does your problem relate to?

The problem seems React related

### React-Unity-WebGL Version

9.4.0

### React Version

18.2.0

### Unity Version

2022.3.16

### What happened?

full screen option is working for all other operating systems, like android, windows, mac book. I already checked for different browsers. all other devices are performing good. on I phone only things full screen option is not working. what would be the solution please guid me
 

### Reproducible test case

`    const { unityProvider, requestFullscreen, loadingProgression, isLoaded } = useUnityContext({
       "loader-url",
       "data-url",
       "frame-work-url",
       "code-url",
    });

    function handleClickEnterFullscreen() {
        requestFullscreen(true);
    }`

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jahansoft** [comment]
please fix this bug, or guid me if I am doing wrong

**Comment by jeffreylanters** [comment]
https://caniuse.com/?search=fullscreen fullscreen is only available on iPad, not on iPhone.
