### ISSUE TITLE
Communication From Unity on Quitted Fails

### ISSUE THREAD

**Issue by Fallc** [jeffreylanters/react-unity-webgl#69]
I tried to invoke a function inside React after Unity has quitted, but it doesn't seem to trigger the function.

In my console, it correctly logs that the application has quitted.

<img width="1309" alt="Bildschirmfoto 2019-06-25 um 17 03 26" src="https://user-images.githubusercontent.com/22775549/60170883-aa409e80-9809-11e9-917a-328771f2fed7.png">

However, the function or the console.log() specified in the callback never gets triggered.

```
constructor(props) {
        super(props);

        // Next up create a new Unity Content object to 
        // initialise and define your WebGL build. The 
        // paths are relative from your index file.

        this.unityContent = new UnityContent(
            "/Blocks/Build.json",
            "/Blocks/UnityLoader.js"
        );

        // this.unityContent.on("finishBlocksFromUnity", () => {
        //     this.props.toNewWords();
        // });

        this.unityContent.on("quitted", () => {

            // Now we can for example go back to another page
            console.log("Log quitted")
            this.props.toNewWords();
        });
    }
```

The Unity application gets quitted with `Application.Quit();`.

Did I miss something?

**Comment by jeffreylanters** [comment]
Which version of Unity are you using? This is supported from version 2019.1.x

**Comment by Fallc** [comment]
I'm using version 2019.3.0a5.

**Comment by Fallc** [comment]
The other preconfigured events like loaded or onprogress are working, only quitted doesn't.

**Comment by colinschoen** [comment]
I am also running into this

**Comment by jeffreylanters** [comment]
Since I cannot catch the Application.Quit event that Unity invokes. You should instead send an event yourself, the quitted event will only be invoked when Unity will be unmounted in your application and thus unloaded from memory.

**Comment by colinschoen** [comment]
Sounds good. That is what I ended up doing and all is working well. Thanks for the tip.
