### ISSUE TITLE
Passing more argument in send method.

### ISSUE THREAD

**Issue by robertobrogi** [jeffreylanters/react-unity-webgl#70]
Hi all, is possible to send more arument in send function?
example:

this.unityContent.send(
      "Registry",
      "ChangeScene",
      {scene, data}
    )

thanks a lot

**Comment by jeffreylanters** [comment]
Hi. Sorry, no. Unity does not support receiving multiple values. You could send a string with separators and split them back in Unity to send multiple values. You can read more about ["JavaScript to UnityScript values" here](https://github.com/elraccoone/react-unity-webgl/wiki/JavaScript-to-UnityScript-types). Hope this answers your question.

**Comment by robertobrogi** [comment]
ok thanks for the information :)

i send a obj string and that's it

**Comment by BradStapleton** [comment]
I recommend using Json for complex objects
