### ISSUE TITLE
Adjusting unity window size

### ISSUE THREAD

**Issue by CineTek** [jeffreylanters/react-unity-webgl#9]
Hi is there some way to adjust the gamewindow size like in regular webgl builds? Currently it stretches across the whole screen by using the default Unity component in React

**Comment by jeffreylanters** [comment]
Yes, you can adjust it size of the player with css using the .unity classname.

**Comment by jeffreylanters** [comment]
I also added optional height and width props in version 6.2.0, see [this link](https://github.com/jeffreylanters/react-unity-webgl#width-and-height).
