### ISSUE TITLE
TypeError: this.props.unityContent is undefined when calling setState while scene is running

### ISSUE THREAD

**Issue by quentin-dev** [jeffreylanters/react-unity-webgl#94]
**Describe the bug**
I have a page with a button and a Unity scene. When the button is clicked it calls setState to update an integer stored in the component's state. However, instead of it working successfully I get an error message which says:

```
TypeError: this.props.unityContent is undefined
./node_modules/react-unity-webgl/distribution/components/Unity.js/Unity</Unity.prototype.render
```

**To Reproduce**
1. Have a component render a scene and a button
2. Have the button's onClick method call setState
3. Launch the project & click on the button

**Expected behavior**
The int in the state to be incremented correctly

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version 75.0

**Comment by jeffreylanters** [comment]
Have you defined the Unity content to the component? I need some code to help you any further.

**Comment by quentin-dev** [comment]
```Typescript
import React from 'react';
import Unity from 'react-unity-webgl';
import { UnityContent } from 'react-unity-webgl';
import { Button } from '@material-ui/core/';

interface State {
    currentIndex: number;
    scenes: UnityContent[];
}


export class UnityCarousel extends React.Component<{}, State> {
    constructor(props: {}) {
        super(props);

        this.state = {
            currentIndex: 0,
            scenes: [
                new UnityContent('VolcanoScene/Build.json', 'VolcanoScene/UnityLoader.js'),
                new UnityContent('PlanetScene/Build.json', 'PlanetScene/UnityLoader.js'),
            ]
        };

        this.incrementSceneIndex.bind(this);
    }

    incrementSceneIndex(e: React.MouseEvent<HTMLButtonElement, MouseEvent>): void {
        e.preventDefault();

        const nextIndex: number = this.state.currentIndex + 1;

        this.setState({
            currentIndex: nextIndex,
        });

        console.log(this.state.currentIndex);
    }

    render(): JSX.Element {
        return (
            <div className="UnityCarousel">
                <h1>Unity carousel</h1>
                <Button
                    variant="contained"
                    color="primary"
                    onClick={e => {
                        this.incrementSceneIndex(e);
                    }}
                >
                    Next scene
                </Button>
                <Unity unityContent={this.state.scenes[this.state.currentIndex]} />
            </div>
        );
    }
}
```

Here is the relevant code. I'm trying to dynamically change the current scene without reloading the page, upon further inspection it does seem like the error appears when accessing an index for a scene that doesn't exist.

**Comment by jeffreylanters** [comment]
I'm not sure if it causes the problem, but it's not a good practice to store your 'scenes' in your state since they will never change. You can keep them somewhere constant, your component will handle the rest since the current index will change. It's also not a good idea to swap Unity instances like this, Unity is know for very poor and unstable resource management. This will most likely cause memory issues. For more details see #22.
