### ISSUE TITLE
Dinamically serve UnityContents (e.g.: from database) 

### ISSUE THREAD

**Issue by Geraldo-Neto** [jeffreylanters/react-unity-webgl#99]
On our project, we a using **multiple Unity builds**, but every time we have a new one, we have to republish the project, because the unity build files are static under the **"public"** folder.

Is it possible to load UnityContents (i.e. the build itself) without using static files under "public/MyGame/Build.json" and "public/MyGame/UnityLoader.js"?

It would be great if we could load it dinamically, for instance, from a database (we are using MongoDB).

Is there any other solutions for this, currently?

Thank you in advance. This is a really heplful repo.

**Comment by jeffreylanters** [comment]
Hi, you can serve your json and js file from anywhere. Keep in mind to set your cross origin settings. Good luck!
